### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jantimon** [typicode/husky#349] opened 2018-09-17 13:24 UTC
Hi

I am using `husky 1.0.0-rc.14` and on some machines (with an old node version) husky fails with `SyntaxError: Use of const in strict mode.`

Would it be possible to transpile husky to work with every node version?

Might also solve issues with SourceTree or GitKraken where no `.bash_prompt` is executed and node falls back to an ancient version. E.g.: #243

**Comment by typicode** [comment] 2018-10-02 00:27
Hi @jantimon,

Unfortunately, I don't think it will be possible to go lower than Node 6 as IIRC some dependencies requires it.

That said, [please-upgrade-node](https://github.com/typicode/please-upgrade-node) should have caught it and displayed a better error message.

Do you remember if you got something like `husky requires at least version 6 of Node, please upgrade` before the SyntaxError?

Maybe this needs to be changed https://github.com/typicode/husky/blob/master/husky.js#L1-L2

**Comment by jantimon** [comment] 2018-10-02 08:33
You could compile the entire app (including dependencies) - I know that's not perfect but would solve issues for people who are using an old system node version

**Comment by typicode** [comment] 2018-10-02 10:32
Maybe, but personally I feel it would be too much effort ^^

Generally speaking, husky will follow the [Node releases](https://github.com/nodejs/Release) down to the maintenance LTS (Node 6 currently). And a major version will be published when Node 6 will be end-of-life.

If you really need to support an old version of Node, you can use husky `0.14.3`.  It's really stable and works quite well.

I'm closing the issue as I couldn't reproduce the `SyntaxError` with Node `0.10`:

```sh
npm i husky -D
npm WARN engine husky@1.1.0: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})

> husky@1.1.0 preuninstall /tmp/husky-node-0.12/node_modules/husky
> node husky uninstall

Husky requires Node 6, skipping Git hooks installation.
npm WARN engine cosmiconfig@5.0.6: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine execa@0.9.0: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
# ...
npm WARN engine p-try@2.0.0: wanted: {"node":">=6"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine esprima@4.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})

> husky@1.1.0 install /tmp/husky-node-0.12/node_modules/husky
> node husky install

Husky requires Node 6, skipping Git hooks installation.
husky@1.1.0 node_modules/husky
├── slash@2.0.0
├── pkg-dir@3.0.0
# ...
```

**Comment by jantimon** [comment] 2018-10-02 13:53
My problem is that I am using `.nodenv` which does not work together with husky.

So during installation it uses node 8 but during githook it falls back to the system node version.

Full stacktrace:

```
node_modules/husky/lib/runner/bin.js:3
const _1 = require("./");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by typicode** [comment] 2018-10-05 10:10
Ok, sorry, I understand better now (by the way `1.1.1` improves the error message, thanks to this issue).

Are you commiting from the terminal or a GUI?

**Comment by jantimon** [comment] 2018-10-05 20:10
I am using an Ui which does not properly loads the bash_profile and therefore will use the system nodejs version

**Closed** 2018-11-28 17:21 UTC
