### ISSUE TITLE
It's failed in git GUI

### ISSUE THREAD

**Issue by NSGUF** [typicode/husky#1041] opened 2021-09-10 06:55 UTC
## It's failed in git GUI 
when i use GUI， eslint failed, but commit succeeded；
westorm、vscode、terminal can intercept,but gui can't；  

"husky": "^7.0.1",

**Comment by thany** [comment] 2021-09-13 01:13
This is a blithering awful issue description. But, he's right. Hooks work perfectly in the CLI, but not in "GUI", and for me the GUI means GitKraken.

I've also reported it to them. The precommit hook, at least, does get executed when committing from within VScode (graphically, not the CLI in VScode... obviously) so I'm guessing GitKraken is doing something wrong. How the hell they convince Git to commit without executing hooks? Your guess is as good as mine, but they are definitely messing *something* up.

And this may be the case for @NSGUF as well, even with that much detailed information and environmental context.

**Comment by typicode** [comment] 2021-09-13 21:59
It's a known issue on GitKraken
https://github.com/typicode/husky/issues/875

Unfortunately nothing that could be done on husky's side.

As for the other problem, I'd suggest checking https://typicode.github.io/husky/#/?id=command-not-found as it's often a PATH problem.

**Comment by Peterabsolon** [comment] 2021-09-21 09:19
What a joke

**Comment by sholladay** [comment] 2021-09-22 01:07
It's a regression that the Husky maintainers just don't want to fix.

See: https://github.com/typicode/husky/issues/639

**Comment by mlbiche** [comment] 2021-09-23 13:53
Seems to be fixed in GitKraken 8

**Comment by thany** [comment] 2021-09-24 08:07
Nice, thanks for staying on the ball 🙂

**Comment by Naddiseo** [comment] 2021-11-29 18:12
Another workaround I found is a little bash file to fill in the .git/hooks files and make them run the husky hooks:
```bash
#!/bin/sh
# ./hook_setup.sh
set -e

HERE=$(realpath $(dirname "$0"))
GITDIR="$HERE/.git"
HOOKDIR="$GITDIR/hooks"
HUSKY_HOOKS="$HERE/.husky"

for F in `ls "$HUSKY_HOOKS"`; do
    P="$HUSKY_HOOKS/$F"
    if [ -f "$P" ] ; then
        HOOK_FILE="$HOOKDIR/$F"
        echo "#!/bin/sh" > "$HOOK_FILE"
        echo "sh \"$P\"" >> "$HOOK_FILE"
        chmod +x "$HOOK_FILE"
    fi
done
```

then call it in the `prepare` script: 
```json
{
    "scripts": "husky install && sh hook_setup.sh"
}
```

**Comment by Naddiseo** [comment] 2022-01-28 20:52
still an issue

**Comment by typicode** [comment] 2022-02-17 04:26
I'm going to close this issue as it seems to be fixed in GitKraken now:
https://davideimola.com/git-hooks-gitkraken-client-husky-nvm/

As for why it doesn't work in GUI (and how to fix it) the article explains it very well:

> Node version manager work by modifying the PATH when the terminal is started. For this reason, GUI clients usually do not work well whit those managers as they are not sourcing .zshrc or .bashrc files where nvm is initialized.

If you install node globally (without nvm) you shouldn't have this issue though.

**Closed by typicode** 2022-02-17 04:26 UTC

**Comment by Naddiseo** [comment] 2022-02-17 04:38
> I'm going to close this issue as it seems to be fixed in GitKraken now: https://davideimola.com/git-hooks-gitkraken-client-husky-nvm/
> 
> As for why it doesn't work in GUI (and how to fix it) the article explains it very well:
> 
> > Node version manager work by modifying the PATH when the terminal is started. For this reason, GUI clients usually do not work well whit those managers as they are not sourcing .zshrc or .bashrc files where nvm is initialized.
> 
> If you install node globally (without nvm) you shouldn't have this issue though.

I'm not using nvm :) 
the issue with git gui seems to be that it [doesn't use core.hookPath](https://github.com/prati0100/git-gui/issues/62) so I've been relying on the little script I posted a few replies back to run on the `"prepare"` script to install husky properly

**Comment by sholladay** [comment] 2022-02-23 07:34
I'm also not using nvm. I have Node and npm installed globally via Homebrew. Nothing fancy about the setup, just the default installation location.

**Comment by typicode** [comment] 2022-02-24 00:15
@Naddiseo I see

@sholladay have you tried also https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities?

**Comment by sholladay** [comment] 2022-02-24 06:20
No, because:
1. I assume there is a reason that macOS is designed that way.
2. I don't want to make such modifications to all of the machines that I interact with on an ongoing basis. It's not ergonomic, among other reasons.
