### ISSUE TITLE
Husky Segmentation fault error | Node 18

### ISSUE THREAD

**Issue by smo043** [typicode/husky#1246] opened 2023-03-17 00:57 UTC
I'm using the latest version of Husky 8.0.3 with yarn 3.4.1. I had a pre-push function that was working perfectly until I upgraded the node version to 18.14.0 from 16*. I began seeing the following error on both MAC and Windows:

.husky/pre-push: line 5: 36530 Segmentation fault: 11

Any help would be greatly appreciated.

Thank you!

**Comment by typicode** [comment] 2023-03-17 04:01
It may be a duplicate of #1233 
What's the failing command?

**Comment by smo043** [comment] 2023-03-17 11:45
sh - pre-push

yarn pre-push

In package.json:
"pre-push": "yarn lint && yarn test"

**Comment by typicode** [comment] 2023-03-18 09:50
Thanks. I don't think it's something that can be fixed on husky's side. AFAIK there's nothing fancy in husky's script (see `. husky/_/husky.sh`) that you would cause it. If you run `yarn pre-push` manually do you have a seg fault?

**Comment by smo043** [comment] 2023-03-18 12:26
Running yarn pre-push manually works fine, but it fails with husky scripts. Husky functioned normally prior to the node update to 18+.

**Comment by smo043** [comment] 2023-03-29 04:58
@typicode - looking for help

**Comment by krzysztof-kabala** [comment] 2023-03-30 08:47
the same for me
```
yarn --version
1.22.19
node --version
v18.15.0
// package.json
 "dependencies": {
    "husky": "^8.0.3"
  },
```

.husky/pre-commit
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged
```

```
git -c [...]
.husky/pre-commit: line 5: 29163 Segmentation fault: 11  yarn lint-staged
```

But `.husky/pre-commit` as a console command works good

**Comment by smo043** [comment] 2023-04-29 02:51
Any help???

**Comment by krzysztof-kabala** [comment] 2023-07-06 10:49
> the same for me (macOS 13.2.1 (22D68) M1 Pro)
> 
> ```
> yarn --version
> 1.22.19
> node --version
> v18.15.0
> // package.json
>  "dependencies": {
>     "husky": "^8.0.3"
>   },
> ```
> 
> .husky/pre-commit
> 
> ```
> #!/usr/bin/env sh
> . "$(dirname -- "$0")/_/husky.sh"
> 
> yarn lint-staged
> ```
> 
> ```
> git -c [...]
> .husky/pre-commit: line 5: 29163 Segmentation fault: 11  yarn lint-staged
> ```
> 
> But `.husky/pre-commit` as a console command works good

Update

```
❯ yarn --version
1.22.19
❯ node --version
v18.16.1
```

```
# upgrade husky
node husky install  
```
Husky `v8.0.3` and Node `v18.16.1` works good! `Segmentation fault` gone away ! :)

**Comment by longprao** [comment] 2023-07-29 04:23
I have got the same error on Node 18, and fixed it by changing from `yarn lint-staged` to `npx lint-staged`

**Comment by little-buddy** [comment] 2023-08-28 10:36
npx is ok.
I can't understand why yarn doesn't work🤷🏻‍♀️

**Comment by veryvorobey** [comment] 2024-01-10 16:30
> I have got the same error on Node 18, and fixed it by changing from `yarn lint-staged` to `npx lint-staged`

Got the same error with:
Apple M3 Max
node v20.10.0
yarn 1.22.21

Replacement of "yarn" with "npx" (for packages) or "npm run" (for scripts) solved the problem 😌

**Closed** 2024-01-25 15:49 UTC

**Comment by ConorFayleTCO** [comment] 2024-03-25 15:11
I used [n](https://www.npmjs.com/package/n) to install a version of node that worked.
```
$ npm install -g n
$ n 18.16.1
```
It then worked fine with yarn again.
