### ISSUE TITLE
Hook should fail if command is not found

### ISSUE THREAD

**Issue by seyfert** [typicode/husky#715] opened 2020-04-18 18:56 UTC
Husky should fail a hook if the package manager husky is configured to run cannot be found.

The reason this came up is that SourceTree has an issue with the PATH not including /usr/local/bin on MacOS by default.  So if a developer doesn't have SourceTree setup correctly it will commit the change since the hook is skipped by Husky when the command is not found.

See this related SourceTree issue.
https://jira.atlassian.com/browse/SRCTREE-7184

Other related husky issues:
https://github.com/typicode/husky/issues/390
https://github.com/typicode/husky/issues/639

Shouldn't the hook error (exit 1) if the command is not found instead of skipping the hook?

https://github.com/typicode/husky/blob/85a47046c5cf1ae26072fbf39f5f01fdde1cae34/sh/husky.sh#L25-L28

In the example below I am trying to list my project using a yarn script as a pre-commit hook but I purposely removed yarn from my PATH.

```sh
~/test$ git --version
git version 2.20.1 (Apple Git-117)
~/test$ HUSKY_DEBUG=1 git commit -m "test commit"
husky:debug husky v4.2.3 - pre-commit
husky:debug Current working directory is /Users/.../test
Can't find yarn in PATH: /Library/Developer/CommandLineTools/usr/libexec/git-core:/usr/bin:/bin:/usr/sbin:/sbin
Skipping pre-commit hook
husky:debug husky v4.2.3 - prepare-commit-msg
husky:debug Current working directory is /Users/.../test
husky:debug prepare-commit-msg config not found, skipping hook
husky:debug husky v4.2.3 - commit-msg
husky:debug Current working directory is /Users/.../test
husky:debug commit-msg config not found, skipping hook
husky:debug husky v4.2.3 - post-commit
husky:debug Current working directory is /Users/.../test
Can't find yarn in PATH: /Library/Developer/CommandLineTools/usr/libexec/git-core:/usr/bin:/bin:/usr/sbin:/sbin
Skipping post-commit hook
[test-branch 06cb01a] test commit
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by zuzusik** [comment] 2020-04-21 23:57
Very good suggestion. Due to Husky breaking changes (actually, I'd rather consider it a regression) after moving to husky 4 all the commit hooks just started to be skipped suddenly when doing commit through SourceTree. It took me quite a while to figure out what's going on.

**Comment by drwaky** [comment] 2020-09-24 00:04
Same here with husky 4, Sourcetree, and MacOs. I moved back to husky 3.1.0.

Any solution?

**Comment by qqilihq** [comment] 2020-11-20 18:12
Same here. Wondering why hooks did not run using Fork.app on Mac. Downgrading to 3.1.0 fixed this.

Feels like a regression to me.

**Comment by typicode** [comment] 2021-01-08 18:16
Behavior is changed in v5 and it will fail if a command is missing.
Thanks for the feedback :+1:

**Closed by typicode** 2021-01-08 18:16 UTC

**Comment by luanmuniz** [comment] 2021-03-29 13:40
Still a problem in v6
