### ISSUE TITLE
Git LFS and husky prepush hook?

### ISSUE THREAD

**Issue by orlin** [typicode/husky#108] opened 2017-03-08 16:28 UTC
I just tried to `husky` a `prepush` script and nothing happened.  Looking at `.git/hooks/pre-push` I see that I already have a hook there:

```
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

Running `node node_modules/husky/bin/install.js` doesn't help:

```
husky
setting up hooks
skipping pre-push hook (existing user hook)
done
```

I guess that's good, as I don't want Git LFS to break and get some large files in the repo without noticing...

Is there a husky solution for having a prepush while also using [git-lfs](https://github.com/git-lfs/git-lfs)?

**Comment by typicode** [comment] 2017-03-13 11:56
Hi @orlin,

Good question. Would it be possible to move the logic out of the `pre-push` hook and have `husky` run it on `pre-push`?

```sh
{
  "scripts": {
    "prepush": "node ./scripts/git-lfs-exists.js"
  }
}
```

**Comment by joncursi** [comment] 2017-06-04 05:43
@typicode I'm having the same issue. Willing to try it out but I'm not sure how to convert the git-lfs code to JS

**Comment by KidsKilla** [comment] 2017-07-26 17:39
@typicode No.

package.json
`"prepush": "git lfs pre-push \"$@\"",` or `"prepush": "git lfs pre-push",`

```
husky > npm run -s prepush (node v8.1.2)

This should be run through Git's pre-push hook.  Run `git lfs update` to install it.
```

I suppose LFS requires parameters: https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks
```
The pre-push hook runs during git push, after the remote refs have been updated but before any objects have been transferred. It receives the name and location of the remote as parameters, and a list of to-be-updated refs through stdin. You can use it to validate a set of ref updates before a push occurs (a non-zero exit code will abort the push).
```

**Comment by KidsKilla** [comment] 2017-07-26 17:48
What would probably solve the issue: ability to add hooks code instead of replacing it.
For example:
`"postinstall": "git lfs update --force && cd ./node_modules/husky && npm run install -- --append"`

**Comment by rcalabro** [comment] 2017-12-08 18:12
+1

**Comment by creaux** [comment] 2017-12-27 16:22
+1

**Comment by L0stSoul** [comment] 2018-01-10 04:32
i have the same problem and to solve it i migrate from husky to git-hooks. both library is pretty similiar but git-lfs hooks work pretty well with git-hooks :)

**Comment by dperyel** [comment] 2018-03-19 17:02
Try to add $GIT_PARAMS into your prepush script `git lfs pre-push $GIT_PARAMS`. 
Or make some prepush.sh script with `command -v git-lfs >/dev/null && git lfs pre-push "$@"` and call it from your package.json prepush: `sh ./prepush.sh $GIT_PARAMS`

**Comment by rcalabro** [comment] 2018-04-07 03:32
+1

**Comment by Buthrakaur** [comment] 2018-09-24 13:04
@GregTheGreek I switched to `git-hooks-plus` because of this problem and it works just well.

**Comment by GregTheGreek** [comment] 2018-09-24 13:05
Amazing thanks!

**Comment by pimjansen** [comment] 2018-11-02 11:31
Have the same issue, i'd rather not switch again to a new tool.
Any update on this?

**Comment by jmchambers** [comment] 2018-11-06 05:14
I've managed to get this working with the latest version of husky (1.1.3):

**package.json**

```json
  "husky": {
    "hooks": {
      "pre-push": "hooks/pre-push-lfs $HUSKY_GIT_PARAMS <<< $HUSKY_GIT_STDIN"
    }
  }
```

The trick was figuring out how to set STDIN for the command, using `<<< $HUSKY_GIT_STDIN`.

The script `hooks/pre-push-lfs` is just a file I created with the content that `git lfs update --manual` gives you:

**hooks/pre-push-lfs**

```bash
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

Be sure to make it executable:

```
chmod +x hooks/pre-push-lfs
```

This got pre-push working for me. I think the other hooks probably need the same setup too (though haven't test this yet):

**package.json**

```json
  "husky": {
    "hooks": {
      "post-checkout": "hooks/post-checkout-lfs $HUSKY_GIT_PARAMS <<< $HUSKY_GIT_STDIN",
      "post-commit": "hooks/post-commit-lfs $HUSKY_GIT_PARAMS <<< $HUSKY_GIT_STDIN",
      "post-merge": "hooks/post-merge-lfs $HUSKY_GIT_PARAMS <<< $HUSKY_GIT_STDIN",
      "pre-push": "hooks/pre-push-lfs $HUSKY_GIT_PARAMS <<< $HUSKY_GIT_STDIN"
    }
  }
```

Hope that helps.

**Comment by Fandekasp** [comment] 2018-12-07 07:20
After reading a bit about here-strings, I modified the hook calls as follow
```
"echo $HUSKY_GIT_STDIN | hooks/pre-push-lfs $HUSKY_GIT_PARAMS"
```

**Comment by Fandekasp** [comment] 2019-02-26 02:39
Just realized that somehow the `.git/hooks/pre-push` script got overrided with the git lfs hook code... not sure when and why

**Comment by mattrabe** [comment] 2019-05-17 20:05
To summarize suggestions by @jmchambers and @Fandekasp, the following works for me and keeps the hooks under version control as desired:

1. Run `git lfs update --manual`
1. Copy each of the scripts the above command spits out into new files under version control. **NOT** into the .git/hooks/ dir, but instead into a new dir in your repo at hooks/. Name them hooks/pre-push-lfs, hooks/post-checkout-lfs, etc
1. Point husky to the files you just saved in package.json:

```
  "husky": {
    "hooks": {
      ...your other hooks...
      "pre-push": "echo $HUSKY_GIT_STDIN | hooks/pre-push-lfs $HUSKY_GIT_PARAMS",
      "post-checkout": "echo $HUSKY_GIT_STDIN | hooks/post-checkout-lfs $HUSKY_GIT_PARAMS",
      "post-commit": "echo $HUSKY_GIT_STDIN | hooks/post-commit-lfs $HUSKY_GIT_PARAMS",
      "post-merge": "echo $HUSKY_GIT_STDIN | hooks/post-merge-lfs $HUSKY_GIT_PARAMS"
    }
  }
```

Yes, this does mean that if those hooks for LFS ever change that your hook files would need to be updated to stay in sync, but if you look at those hooks files they are pretty inert - they just call the git lfs commands that must possess the actual business logic for the hooks. So I would estimate that is a minor issue - and would be easily solved after a future breaking change by repeating the here-entailed process of saving the hooks from `git lfs update --manual` to files, easily enforced by noticing that running `git lfs update` spits out an error after said future update, just like the first time you ran into this which brought you here...

**Comment by mbelsky** [comment] 2019-07-16 09:35
@mattrabe thanks for summary. However there is an issue with that solution. After clone `.git/hooks` will contain a few `.sample` files and four hooks generated by `git lfs`:

- post-checkout
- post-commit
- post-merge
- pre-push

And husky won't overwrite that hooks on `npm install`. So be careful.

**Comment by mattrabe** [comment] 2019-08-21 16:51
@mbelsky I believe your statement to be correct regarding files in .git/hooks - however, if I am reading correctly it does not affect my summary above, because the files in my summary are in `hooks/`, not in `.git/hooks/`. That is after all the whole point: put them somewhere other than below the .git dir so that they can be version controlled

**Comment by mbelsky** [comment] 2019-09-13 07:59
@mattrabe I've created a simple [repo](https://github.com/mbelsky/husky-with-lfs) with husky and lfs. To reproduce the issue that I described, please do following steps:

1. Check that git lfs is installed on your machine `git lfs --version`
2. `git clone https://github.com/mbelsky/husky-with-lfs.git`
3. `cd ./husky-with-lfs`
4. `npm i`
5. `git checkout -b repro-108`
6. `husky` doesn't call `post-checkout` hook

## Expected result:
On `post-checkout` hooks husky echo `👋 Hey everyone from typicode/husky/issues/108`

## Why?
This happens because after cloning `git lfs` create a few hooks in `.git/hooks` folder and `npm i` doesn't overwrite them with `husky` hooks. There is an [PR](https://github.com/typicode/husky/pull/535) that could solve that issue.

**Comment by aviaryan** [comment] 2019-09-26 15:58
Did anyone else have success with `git-hooks-plus` as @Buthrakaur mentions or the original project [git-hooks-js](https://github.com/tarmolov/git-hooks-js)?

**Comment by aviaryan** [comment] 2019-09-27 09:32
@mbelsky I think if we just add a step 3.5 in there where we manually go to the `hooks` directory and delete all LFS hooks, then step 4, we can make this work. Not the best solution but this can be manageable for a small team.

**Comment by mbelsky** [comment] 2019-09-27 09:37
@aviaryan absolutely right. However this step break lfs support for a repo. So in addition it requires 4.5 step where a user manually merge lfs hooks in husky hooks.

**Comment by aviaryan** [comment] 2019-09-27 09:58
@mbelsky Sorry but I don't see how we need that step. If we go by @mattrabe's [post](https://github.com/typicode/husky/issues/108#issuecomment-493582447), LFS hooks should be already placed by husky (at `npm i`) since `package.json` and `$project_root/hooks` directory already has those hooks.

PS - It could be that I don't get how `husky` works. I am just working on a project that already has husky set up and I need to use LFS now.

**Comment by mbelsky** [comment] 2019-09-27 10:03
@aviaryan oh I've missed that we placed lfs hooks under `$project_root/hooks`.  If we did it then we don't need to do this `4.5` step. `npm i` writes `husky` hooks under `$project_root/.git/hooks` and later husky hooks will trigger lfs hooks if need

**Comment by danbohea** [comment] 2019-10-31 15:47
Just tried @mattrabe 's [suggestion](https://github.com/typicode/husky/issues/108#issuecomment-493582447) but I always get push failed:
```sh
 > running pre-push hook: echo $HUSKY_GIT_STDIN | hooks/pre-push-lfs $HUSKY_GIT_PARAMS
This should be run through Git's pre-push hook.  Run `git lfs update` to install it.
pre-push hook failed (add --no-verify to bypass)
```
I'm running [yorkie](https://github.com/yyx990803/yorkie) (for of huskie with no issue queue of its own) rather than huskie [because Vue CLI 3](https://cli.vuejs.org/guide/cli-service.html#git-hooks) but I'm lead to believe that they're similar enough.

Any pointers?

**Comment by mattrabe** [comment] 2019-10-31 16:02
@danbohea Did you run `git lfs update` as stated in the error?

**Comment by danbohea** [comment] 2019-10-31 19:12
@mattrabe No I didn't, I thought that this would attempt to write to the .git/hooks/pre-push file that yorkie has already written to. Shall I run it anyway?

**Comment by danbohea** [comment] 2019-10-31 19:20
@mattrabe I ran it:
```sh
$ git lfs update
Hook already exists: pre-push

        #!/bin/sh
        #yorkie 2.0.0
        
        command_exists () {
        command -v "$1" >/dev/null 2>&1
        }
        
        has_hook_script () {
        [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
        }
        
        # OS X and Linux only
        load_nvm () {
        # If nvm is not loaded, load it
        command_exists nvm || {
        export NVM_DIR="$1"
        [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
        }
        }
        
        # OS X and Linux only
        run_nvm () {
        # If nvm has been loaded correctly, use project .nvmrc
        command_exists nvm && [ -f .nvmrc ] && nvm use
        }
        
        cd "."
        
        # Check if pre-push is defined, skip if not
        has_hook_script pre-push || exit 0
        
        # Add common path where Node can be found
        # Brew standard installation path /usr/local/bin
        # Node standard installation path /usr/local
        export PATH="$PATH:/usr/local/bin:/usr/local"
        
        # Try to load nvm using path of standard installation
        load_nvm /home/dan/.nvm
        run_nvm
        
        # Export Git hook params
        export GIT_PARAMS="$*"
        
        # Run hook
        node "./node_modules/yorkie/src/runner.js" pre-push || {
        echo
        echo "pre-push hook failed (add --no-verify to by

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
```

**Comment by mattrabe** [comment] 2019-10-31 19:34
@danbohea Hm, I wish I could help out - I have not experienced that before.

**Comment by mbelsky** [comment] 2019-11-01 09:24
Hey @danbohea 
I've adapted @mattrabe 's suggestion to a manual. Please, try it: https://dev.to/mbelsky/pair-husky-with-git-lfs-in-your-javascript-project-2kh0

**Comment by danbohea** [comment] 2019-11-01 10:23
Thanks @mbelsky I now have something with husky (eventually I need to get this playing nice with yorkie). Your guide really helped me understand what each tool is doing and when, especially when installing/initialising.

**Comment by lolmaus** [comment] 2019-11-12 12:14
Here are commands that work on Windows, as well as *nix:

```json
"husky": {
  "hooks": {
    "pre-commit": "lint-staged",
    "post-checkout": "cross-env-shell echo $HUSKY_GIT_STDIN | cross-env-shell sh lfs-hooks/post-checkout $HUSKY_GIT_PARAMS",
    "post-commit": "cross-env-shell echo $HUSKY_GIT_STDIN | cross-env-shell sh lfs-hooks/post-commit $HUSKY_GIT_PARAMS",
    "post-merge": "cross-env-shell echo $HUSKY_GIT_STDIN | cross-env-shell sh lfs-hooks/post-merge $HUSKY_GIT_PARAMS",
    "pre-push": "cross-env-shell echo $HUSKY_GIT_STDIN | cross-env-shell sh lfs-hooks/pre-push $HUSKY_GIT_PARAMS"
  }
},
```

The `cross-env` npm package must be installed as a dev-dependency:

```
npm i -D cross-env
yarn add -D cross-env
```

**Comment by FullStackForger** [comment] 2020-03-07 17:24
@lolmaus  or @mattrabe solution. What if I want to run `lint-staged` in `pre-push` hook?

**Comment by FullStackForger** [comment] 2020-03-07 17:53
> @lolmaus or @mattrabe solution. What if I want to run `lint-staged` in `pre-push` hook?

Ignore above. Command chaining simply does the job. No need for anything fancier.
```
 "pre-push": "yarn build && bash echo $HUSKY_GIT_STDIN | bash lfs-hooks/pre-push $HUSKY_GIT_PARAMS"
```

Might not look pretty but for multiple commands but those can either be wrapped in npm script command or run as bash script that exits with non 0 for errors.

**Comment by ismay** [comment] 2020-05-11 12:57
Reading through this issue it seems like there are a lot of potential solutions, but tbh. I'd like feedback from the lib author as to what is a canonical solution to this problem from husky's perspective.

The original question in the top comment was: 

> Is there a husky solution for having a prepush while also using git-lfs?

@typicode, when you have time, it'd be nice to have your feedback on what you'd prefer as the solution. Ideally we'd then also add a test case to ensure that the canonical solution won't break. Until then I don't feel safe implementing this in a project.

**Comment by jdtzmn** [comment] 2020-05-29 17:58
Not sure how to test it, but I think this code might work.

Can someone take a look: #729?

**Comment by typicode** [comment] 2021-04-04 18:59
Closing as it should be easier now to use Git LFS with husky's new approach.

**Closed by typicode** 2021-04-04 18:59 UTC

**Comment by sag1v** [comment] 2022-04-05 08:59
@typicode Can you share a link to a resource (or explain here) that explains why or how husky@V5 solves this issue?

**Comment by ericksprengel** [comment] 2023-02-16 05:43
@sag1v

husky v4 installs husky on default git hooks folder `.git/hooks` and the custom hooks in `package.json`.
While husky v8 changes git hooks folder from `.git/hooks/` to `.husky/` and our custom hooks are in shell script files in `.husky/` instead of in the `package.json`.

As we can see in the below example, after migrating to `v8`, I added the git lfs install to `.husky/pre-push` 

⚠️ migrate to v8 before installing lfs (`git lfs install`) https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8


## My migration from v4 to v8 (adding git-lfs too)

**IT IS JUST AN EXAMPLE FOR `pre-push`, GIT LFS HAS MORE HOOKS (`post-checkout`, `post-commit` and `post-merge` ), USE `git lfs install` TO INSTALL THEM**

### v4
package.json:
```json
  "husky": {
    "hooks": {
      "pre-push": "yarn lint"
    }
  }
```

### v8 (with git-lfs):

package.json:
```json
  "scripts": {
    "prepare": "husky install"
  },
```

.husky/pre-push:
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# my custom hook
yarn lint

# git-lfs hook
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"
```

As we can see, .husky/pre-push is more flexible (shell script), is under git version control and uses the original `.git/hooks` files that are compatible with git lfs install.

I tried to be short, but it's not easy to explain with few words. 😅
