### ISSUE TITLE
lint-staged v10.0.7 doesnt trigger husky v4.2.1 (husky v4.0.0-beta.5 works)

### ISSUE THREAD

**Issue by brendonco** [typicode/husky#667] opened 2020-02-07 10:09 UTC
Hi,

Why lint-staged v10.0.7 doesnt trigger husky v4.2.1? but downgrading to husky v4.0.0-beta.5 works ?

**Comment by fox1t** [comment] 2020-02-07 15:51
This fix works: https://github.com/typicode/husky/issues/618#issuecomment-571407578

Is this an intended behavior of the version 4.x.x?

**Comment by brendonco** [comment] 2020-02-10 02:14
Thanks fox1t saw that comment before.  Let me try that one. Thanks

**Comment by brendonco** [comment] 2020-02-10 03:29
> ```js
> npm run lint-staged
> ```

Doesnt seem to work on husky 4.2.1.

```
"scripts": {
    "lint-staged": "lint-staged",
    "commitlint": "commitlint"
},
  "husky": {
    "hooks": {
      "commit-msg": "npm run commitlint -- -E HUSKY_GIT_PARAMS",
      "pre-commit": "npm run lint-staged && npm test && git add"
    }
  },
"lint-staged": {
    "*.js": [
      "eslint"
    ]
  },

```

**Comment by brendonco** [comment] 2020-02-10 03:39
I'm using node v12.13.1. incase anyone is wondering.

**Comment by fox1t** [comment] 2020-02-11 11:36
This is strange, since we resolved on HospitalRun FE: https://github.com/HospitalRun/hospitalrun-frontend/blob/1f1ea4a47e722a1fd3e41febc2877ff0b85e9364/package.json#L116

**Comment by typicode** [comment] 2021-01-08 19:33
Closing as it may have been fixed since then and there wasn't other similar issues (feel free to re-open if that's not the case).
Thanks for the report :+1:

**Closed by typicode** 2021-01-08 19:33 UTC
