### ISSUE TITLE
Win 10 Github Desktop pre-commit hook

### ISSUE THREAD

**Issue by JosefBredereck** [typicode/husky#1072] opened 2021-11-11 10:48 UTC
Hello, I have a problem with my pre-commit hook or husky in general when using Github Desktop.
On the first look, it seems to be #1038, but the problem is. It works perfectly fine in VS code.

My environment:
Terminal or GUI client: GitHub Desktop v2.9.4 (x64)
System OS: Windows 10
Node Version: v15.14.0
npm Version: 7.7.6

I followed the following guide
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

After that, I have now `"husky": "^7.0.4"` in place and get the following error message:
```
/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```
![grafik](https://user-images.githubusercontent.com/13408112/141284189-c86b9a1d-6ad8-4657-b34e-6583abc42af5.png)

Do I have to configure something in the pre-commit file?

```bash
# file .husky/pre-commit
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint-staged-hook
```

**Comment by typicode** [comment] 2021-11-11 19:15
Hmm that's weird, nowhere husky is calling bash in `husky.sh`

**Comment by JosefBredereck** [comment] 2021-11-12 08:48
It seems that I'm not the only one. Someone else also opened an issue for the desktop app  [desktop/desktop #13307](https://github.com/desktop/desktop/issues/13307)

**Comment by KInGATiLLa** [comment] 2022-01-14 12:27
Same here 😞. I'm using from Github desktop. Vscode is fine. But i like github desktop

My environment

OS: Windows 11 latest
Node: 16.3.2
Npm: 8.3.0
Github desktop: 2.9.6 (x64)

**Comment by VincentVerweij** [comment] 2022-02-13 16:57
It is not Github Desktop I am using here but Visual Studio 2022 which gives me the exact same error.

![image](https://user-images.githubusercontent.com/41574930/153765806-d4e575ba-3102-4a1d-801b-66e4ba97d4ea.png)

While Googling, I did come across issue #1038 and there are some suggestions in there.

Did try to change my .husky/commit-msg from

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit 
```

to 

```
#!/bin/sh
# exit 1 will prevent commit to happen, so you can more easily debug things
echo "it's working" && exit 1 
```

And Visual Studio 2022 did give me the message `it's working` with an error symbol (which is normal).

Next I made sure that in my system PATH environment variable I do have `C:\Program Files\Git\usr\bin\cygpath.exe` included. I do see it when printing out $env:PATH in PowerShell.

Any other suggestions?

**Comment by typicode** [comment] 2022-02-17 06:39
Hmm I'm not using Windows enough to help here. However I have GitHub Desktop 2.9.8 working. I also have Git installed with Git Bash on my machine.

I don't see what could be done on husky's side in terms of code.

**Comment by VincentVerweij** [comment] 2022-02-17 09:13
I guess it is just Visual Studio which is acting weird here. Currently my workaround is to use Visual Studio Code to commit code which works just fine.
So perhaps it is wrong to post this Visual Studio issue in here, as Husky seems to be working ok.

Still if anyone else knows what is going on here, or has a suggestion of fixing or logging this elsewhere, give a shout.

**Comment by typicode** [comment] 2022-02-20 22:00
Closing to clean up issues list, but if anyone has fix ideas feel free to add to this thread.

**Closed by typicode** 2022-02-20 22:00 UTC

**Comment by johannesschobel** [comment] 2022-05-02 09:36
This issue is still a thing and i can confirm this issue as described the latter.
@JosefBredereck , have you found a solution for this?

**Comment by JosefBredereck** [comment] 2022-05-02 10:19
Not for the issue, only a work around. If you go back to node 14 the issue should not appear.

**Comment by johannesschobel** [comment] 2022-05-02 18:35
hmmmmmmmmmmmmmmmm~ i will try tomorrow (hopefully) and report back!
However, this is a serious issue / roadblock for the development with windows and husky 😟

**Comment by johannesschobel** [comment] 2022-05-02 18:36
maybe @typicode has some more information about this issue in the meantime?! Would it help, if we provide a minimal reproduction repository?

**Comment by typicode** [comment] 2022-05-02 22:20
@johannesschobel no more info, sorry :/

**Comment by chall2chall4** [comment] 2022-05-05 09:03
![image](https://user-images.githubusercontent.com/30928762/166892822-9d545976-ceb7-4aeb-abbb-30bf25b6d9ad.png)

**Comment by johannesschobel** [comment] 2022-05-06 18:36
@chall2chall4 is the code repository located within a wsl2 distro?

@typicode : would you be willing to help and track down the issue in order to solve this problem?

**Comment by marie-hughes** [comment] 2022-05-17 17:53
> Not for the issue, only a work around. If you go back to node 14 the issue should not appear.

I am using node 14 and I get the issue so I don't think that's a universal solution

**Comment by LukeGarrigan** [comment] 2022-05-19 12:58
I get this running in Github Desktop:
![image](https://user-images.githubusercontent.com/12545967/169298903-04aaee52-4ced-4cca-b1be-4a38c4b68ba4.png)

It works fine from my current IDE (intellij)

**Comment by Fariarx** [comment] 2022-05-19 14:26
> @Fariarx is the code repository located within a wsl2 distro?
> 
> @typicode : would you be willing to help and track down the issue in order to solve this problem?

Нет, это просто  развёрнутый репозиторий на моей виндовс 11. Конкретно взят отсюда: https://github.com/electron-react-boilerplate/electron-react-boilerplate
Я решил это сменой github desktop на другой клиент. (fork)

**Comment by DoctorDerek** [comment] 2022-09-14 18:54
I added `Git bin` along with both of these to my PATH as well:
`C:\Users\derek\AppData\Local\Yarn\bin`
`C:\Users\derek\AppData\Roaming\npm`

Then as a rule I write `.husky` scripts using `yarn ...` or `npm run ...`... that seems to work well for me.

**Comment by Secreto31126** [comment] 2022-12-28 19:59
Leaving my two cents here, I solved the issue by adding .cmd to the npx call in .husky/pre-commit:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx.cmd lint-staged
```

Wild guess: I noticed I have both a "npx" and "npx.cmd" files in C:/Program Files/nodejs, and they are ordered alphabetically. IIRC, Windows pathing matchs the first file, which turns out to be the one without extension (probably a Linux binary from WSL). Again, wild guess, but maybe WSL is messing around in the issue.

**Comment by monstereat** [comment] 2023-03-01 08:24
> thank you  boss

**Comment by celstark** [comment] 2023-10-29 05:48
> Leaving my two cents here, I solved the issue by adding .cmd to the npx call in .husky/pre-commit:
> 
> ```shell
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> npx.cmd lint-staged
> ```
> 
OMG thank you!

Here's my variant:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ "$OS" == "Windows_NT" ]]; then
  npx.cmd lint-staged
else
  npx lint-staged
fi  
```

**Comment by PittsGitHub** [comment] 2023-12-06 13:04
> > Leaving my two cents here, I solved the issue by adding .cmd to the npx call in .husky/pre-commit:
> > ```shell
> > #!/bin/sh
> > . "$(dirname "$0")/_/husky.sh"
> > 
> > npx.cmd lint-staged
> > ```
> 
> OMG thank you!
> 
> Here's my variant:
> 
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> if [[ "$OS" == "Windows_NT" ]]; then
>   npx.cmd lint-staged
> else
>   npx lint-staged
> fi  
> ```

This fix so very nearly works for me but I'd been using regex as part of my command for prettier:
`"npx.cmd prettier --ignore-path .gitignore \"**/*.+(ts|json)\"`

Which I can't seem to get to work inside husky for the life of me, so for now at least I've given up trying to make GitHub desktop work and just using the VSCode source control
