### ISSUE TITLE
husky:debug npx --no-install husky-run exited with 0 exit code

### ISSUE THREAD

**Issue by christo8989** [typicode/husky#740] opened 2020-06-26 19:22 UTC
macOS Catalina 10.15.5
mac Terminal Version 2.10 (433)
git 2.27
node 12.18
npm 6.14.4
husky 4.2.5

I feel like the push is more likely to succeed when I run the command with `HUSKY_DEBUG=1` but there's no real evidence to back it up. Basically, pre-push always runs (test with coverage for about 2 minutes; it succeeds) and then sometimes the push happens and sometimes it never runs the push. It's very sporadic but I started getting pushes while running HUSKY_DEBUG=1 but I've also gotten it to push without that and it's also failed with it. So yeah, totally sporadic.

I ran the troubleshooting solution and everything seems to be in place. 

In talking with another developer, husky started acting weird about a month ago. Also, my computer is completely new so I'm not sure if that has anything to do with it.

**Comment by adamesque** [comment] 2020-08-25 21:07
We're seeing the same behavior anecdotally around the same time-frame, but with a wildly older version of Husky. Pre-push coverage runs (jest), completes apparently successfully. If I `echo $?` (last exit code) I get a `141` (SIGPIPE?) instead of a 0. Push never runs; no further output is written.

macOS Mohave 10.14.16
git 2.21.1
node 12.16.1
npm 6.13.4
husky 1.1.4 (behavior persists after updating to husky@latest)
zsh

**Comment by tibic** [comment] 2020-08-27 08:30
**error Command "husky-run" not found.**

  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },

**Comment by typicode** [comment] 2021-04-04 21:08
Closing as v6 works differently and may not have this issue.

**Closed by typicode** 2021-04-04 21:08 UTC

**Comment by adamesque** [comment] 2021-04-04 22:19
In case anyone comes back to this closed issue: in our case the root cause was that we switched to a new GHE instance with apparently shorter SSH timeouts and so long test suites running in a pre-push hook were silently timing out where they hadn't before when cloned via ssh. https clones didn't suffer from the same issue.
