### ISSUE TITLE
Having to run `yarn install` on every branch

### ISSUE THREAD

**Issue by CWSites** [typicode/husky#936] opened 2021-04-05 21:50 UTC
**Context**
I've lately setup a `pre-commit` with Husky and I noticed that I am having to run `yarn install` each time I branch for it to work. My husky configurations have already been merged into master and I have latest when creating a new branch off master...why then do I need to run `yarn install` again?

I noticed there is a `.gitignore` file inside of `husky/` which ignores the `_/` that has `husky.sh` inside of it... Is this on purpose? 

**Steps to reproduce**

Husky config merged into master

1. `git fetch` to make sure I have latest
2. `git reset --hard origin/master` which makes sure that my local master matches remote master
3. `git checkout -b my-branch-name`
4. make some code changes, husky should run when I commit... It doesn't.
5. run `yarn install`
6. commit my changes, husky runs.

**Comment by typicode** [comment] 2021-04-06 14:43
Hi @CWSites,

I'm not able to reproduce the issue:

```sh
# Trying with a new project
mkdir foo && cd foo
git init && yarn init -y
npm set-script prepare "husky install"

# Install
yarn
# ...
$ husky install
husky - Git hooks installed
# ...

# Set a pre-commit
yarn husky set .husky/pre-commit "echo hello && exit 1"
git commit -m foo
hello
husky - pre-commit hook exited with code 1 (error)

# Changing branch and doing another commit
git checkout -b test
git commit -m foo
hello
husky - pre-commit hook exited with code 1 (error)
```

**Comment by CWSites** [comment] 2021-04-07 14:40
@typicode is there a reason that `_/husky.sh` is ignored?

**Comment by paleite** [comment] 2021-04-15 22:46
@CWSites Yes, because it is generated on the fly by husky. If it wasn't ignored, any change that husky would make in a later version would require you to also update the `_/husky.sh` file which is just generated anyways. I view it as equivalent to having `node_modules` in `.gitignore` in that sense.

**Comment by typicode** [comment] 2021-05-22 04:20
Perfectly explained by @paleite
Running `yarn install` may not be a bad thing also as dependencies or `yarn.lock` may vary on different branches.

That said, Yarn 2 has a different philosophy with `pnp.js` which is kind of "committed" `node_modules`.

**Closed by typicode** 2021-05-22 04:20 UTC
