### ISSUE TITLE
husky doesn't work after install and set in my project

### ISSUE THREAD

**Issue by Rimin** [typicode/husky#891] opened 2021-03-01 12:45 UTC
i have install husky and then set in `package.json` like this:
```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "prepare-commit-msg": "exec < /dev/tty && git cz --hook || true",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "lint-staged": {
    "*.{js,ts,vue,tsx}": [
      "npm run lint",
      "git add"
    ]
  }
```
and this works in my colleague's computer!   however, it doesn't work in my computer, but we have the same project;
i have tried the following:
reinstall the husky; (uninstall and then install)
reinstall node_modules;
remove the files of my project and clone again; 
but it still didn't work like i have never install and add husky into my project; I have learned that there is a folder called `hooks` in `.git` folder, but after i install and run `git commit`, `hooks`  folder still didn't appear.

my git version：2.30.1；
computer system: mac os;
node version: v12.20.0;
husky: 5.1.2;

**Comment by nanhapy** [comment] 2021-03-02 01:53
Duplicate of #854

**Comment by Rimin** [comment] 2021-03-02 02:29
> Duplicate of #854

yeah, it works for me after i tried
```
yarn husky install
yarn husky add .husky/pre-commit "lint-staged"
sudo npm i lint-staged -g
```
it created `.husky` folder just in the directory of my project. the main command to solve the problem is the second command i ran;

thank you!

**Closed** 2021-03-02 02:30 UTC

**Comment by typicode** [comment] 2021-03-02 05:35
Hi Rimin,

I'd suggest having `lint-staged` installed locally and updating `package.json` scripts so that your colleague have husky installed automatically and be able to run `lint-staged`.

You can run the following commands:

```shell
rm .husky/pre-commit # otherwise husky init will fail
yarn husky init
# edit .husky/pre-commit and replace `npm test` with `yarn lint-staged`

# add lint-staged locally
yarn add lint-staged --dev
```

You can remove `husky` field from `package.json` after that.

**Comment by alisalehi1380** [comment] 2025-05-20 13:46
```git config core.hooksPath .husky```
