### ISSUE TITLE
Husky does not respect jest's exit code 1 

### ISSUE THREAD

**Issue by Aziaev** [typicode/husky#614] opened 2019-11-28 10:38 UTC
Git  2.23.0
node  v12.13.0
npm 6.12.0

I have React TS app with tests created with Jest. 

**Expected:** I want to hooks run all tests before commit and reject commiting if some of tests is failes. 
**Actual:** Hooks starts tests and commits changes anyway, wihthout respect to Jest test failed. Even some of test failes.

Terminal and the following commands output:
```sh
$ HUSKY_DEBUG=1 npm install husky@3.1.0 --save-dev --userconfig=npmrc.properties

> husky@3.1.0 preuninstall C:\Users\user\repo\project\frontend\node_modules\husky
> node husky uninstall

husky:debug Current working directory is 'C:\Users\user\repo\project\frontend\node_modules\husky'
husky:debug INIT_CWD environment variable is set to 'C:\Users\user\repo\project\frontend'
husky > Uninstalling git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: C:/Users/user/repo/project
husky:debug   --git-common-dir: ../../../.git
husky > Done

> husky@3.1.0 install C:\Users\user\repo\project\frontend\node_modules\husky
> node husky install

husky:debug Current working directory is 'C:\Users\user\repo\project\frontend\node_modules\husky'
husky:debug INIT_CWD environment variable is set to 'C:\Users\user\repo\project\frontend'
husky > Setting up git hooks
husky:debug Git rev-parse command returned:
husky:debug   --show-top-level: C:/Users/user/repo/project
husky:debug   --git-common-dir: ../../../.git
husky:debug Installing hooks in '..\..\..\.git\hooks'
husky > Done

> husky@3.1.0 postinstall C:\Users\user\repo\project\frontend\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN @fimbul/ymir@0.15.0 requires a peer of tsutils@>2.29.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-devtools@3.5.0 requires a peer of react-redux@^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ husky@3.1.0
updated 1 package in 26.324s
```

```sh
$ HUSKY_DEBUG=1 git commit -m "commit message"
husky:debug husky v3.1.0 (created at 2019-11-28 13:23:38)
husky:debug pre-commit hook started
husky:debug Current working directory is '/c/Users/user/repo/project'
husky:debug Changed current working directory to 'C:\Users\user\repo\project\frontend'
husky > pre-commit (node v12.13.0)
npm WARN npm npm does not support Node.js v12.13.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/

> pprb-frontend@1.0.0 test C:\Users\user\repo\project\frontend
> jest --config config/jest.config.js

Summary of all failing tests
FAIL .../__tests__/UModalFindSpinner.test.tsx (15.825s)
  ● Spinner test › should match snapshot

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: {}

       6 |   const component = shallow(<Spinner />);
       7 |   test('should match snapshot', () => {
    >  8 |     expect(component).toBe(true);
         |                       ^
       9 |     // expect(component).toMatchSnapshot();
      10 |   });
      11 | });

      at Object.<anonymous> (../Spinner/__tests__/Spinner.test.tsx:8:23)


Test Suites: 1 failed, 2 passed, 3 of 23 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   6 passed, 6 total
Time:        19.878s, estimated 27s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
husky:debug husky v3.1.0 (created at 2019-11-28 13:23:38)
husky:debug prepare-commit-msg hook started
husky:debug Current working directory is '/c/Users/user/repo/project'
husky:debug Changed current working directory to 'C:\Users\user\repo\project\frontend'
husky:debug husky v3.1.0 (created at 2019-11-28 13:23:38)
husky:debug commit-msg hook started
husky:debug Current working directory is '/c/Users/user/repo/project'
husky:debug Changed current working directory to 'C:\Users\user\repo\project\frontend'
husky:debug husky v3.1.0 (created at 2019-11-28 13:23:38)
husky:debug post-commit hook started
husky:debug Current working directory is '/c/Users/user/repo/project'
husky:debug Changed current working directory to 'C:\Users\user\repo\project\frontend'
[feature/XXX-001 50333cef2] commit message
 2 files changed, 4 insertions(+), 3 deletions(-)
```

// jest.config.js
```
module.exports = {
  verbose: true,
  bail: true,
  rootDir: '../src',
  setupFilesAfterEnv: ['../config/setupTests.ts'],
  moduleNameMapper: {
    '\\.(css|less)$': 'identity-obj-proxy',
    '^common$': '<rootDir>/common/index.ts',
    '^common(.*)$': '<rootDir>/common$1',
    '^app(.*)$': '<rootDir>/app$1',
    '^modules(.*)$': '<rootDir>/modules$1',
    '^components(.*)$': '<rootDir>/components$1',
    '^project-ui(.*)$': '<rootDir>/libraries/project-ui/index.ts',
    '^assets(.*)$': '<rootDir>/assets$1',
    '^tasks(.*)$': '<rootDir>/panels/tasks$1',
    '^union$': '<rootDir>/union/index.ts',
    '^notifications(.*)$': '<rootDir>/panels/notifications$1'
  },
  preset: 'ts-jest/presets/js-with-babel',
  snapshotSerializers: ['enzyme-to-json/serializer'],
  testEnvironment: 'jsdom'
};
```

// package.json
```
{
  "name": "frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    ...
    "test": "jest --config config/jest.config.js",
    ...
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
    "husky": "^3.1.0",
    ...
    "jest": "24.8.0",
    ...
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm test || echo SUCCESS"
    }
  }
}
```

// Test that always fail
```
import * as React from 'react';
import { shallow } from 'enzyme';
import Spinner from '../Spinner';

describe('Spinner test', () => {
  const component = shallow(<Spinner />);
  test('should match snapshot', () => {
    expect(component).toBe(true); // always fail
  });
});
```

// pre-commit hook file content
```
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 3.1.0
#   At: 2019-11-28 10:24:10
#   See: https://github.com/typicode/husky#readme

# From
#   Directory: C:/Users/user/repo/project/frontend
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="frontend/node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  if [ "${HUSKY_DEBUG}" = "true" ] || [ "${HUSKY_DEBUG}" = "1" ]; then
    echo "husky:debug $1"
  fi
}

debug "husky v3.1.0 (created at 2019-11-28 10:24:10)"
debug "$hookName hook started"
debug "Current working directory is '`pwd`'"

if [ "${HUSKY_SKIP_HOOKS}" = "true" ] || [ "${HUSKY_SKIP_HOOKS}" = "1" ]; then
  debug "HUSKY_SKIP_HOOKS is set to ${HUSKY_SKIP_HOOKS}, skipping hook"
  exit 0
fi

if [ "${HUSKY_USE_YARN}" = "true" ] || [ "${HUSKY_USE_YARN}" = "1" ]; then
  debug "Calling husky through Yarn"
  yarn husky-run $hookName "$gitParams"
else

  if [ -f "$scriptPath" ]; then
    # if [ -t 1 ]; then
    #   exec < /dev/tty
    # fi
	
    if [ -f ~/.huskyrc ]; then
      debug "Sourcing '~/.huskyrc'"
      . ~/.huskyrc
    fi
    node "$scriptPath" $hookName "$gitParams"
  else
    echo "Can't find Husky, skipping $hookName hook"
    echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
  fi
fi
```

How I can fix it?

**Comment by typicode** [comment] 2020-01-07 02:57
Maybe this is the cause: `"pre-commit": "npm test || echo SUCCESS"`.

`||`  will run `echo SUCCESS` when `npm test` fails. And because `echo SUCCESS` exits with `0` `pre-commit` hook doesn't fail.

`npm test && echo SUCCESS` should do the trick.

I'm closing but feel free to reopen if it doesn't work.

**Closed by typicode** 2020-01-07 02:57 UTC

**Comment by HugoLiconV** [comment] 2020-02-12 22:04
Hi guys! 
I'm having a problem with Jest when I'm trying to push my code and there are no tests found related to files changed since the last commit because it gets stuck here: 
![Screenshot from 2020-02-12 15-03-51](https://user-images.githubusercontent.com/22970186/74381534-e6c90680-4da8-11ea-859a-263ff6e7f3f5.png)
this is my configuration
```
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --watchAll",
    "eject": "react-scripts eject"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged",
      "pre-push": "npm test"
    }
  }
```

**Comment by ajbee07** [comment] 2020-07-08 09:11
any solution on this? still not working

**Comment by LuoTuxiu** [comment] 2020-10-20 04:27
I have the same ploblem, here is my config in package.json
```
  "scripts": {
    "dev": "NODE_ENV=development webpack-dev-server --config webpack/config.js",
    "build": "NODE_ENV=production webpack --config webpack/config.js",
    "lint": "eslint --ext .js,.ts,.jsx,tsx src",
    "fix": "eslint --ext .js,.ts,.jsx,tsx src --fix",
    "test": "jest --passWithNoTests",
    "report": "jest --coverage --findRelatedTests"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "prettier --write",
      "yarn lint",
      "yarn test"
    ],
    "*.{css,less}": [
      "prettier --write"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }
```
my code will commit even if the jest test is failed? any body can help ?

**Comment by andyngdz** [comment] 2021-05-06 15:43
> Hi guys!
> I'm having a problem with Jest when I'm trying to push my code and there are no tests found related to files changed since the last commit because it gets stuck here:
> ![Screenshot from 2020-02-12 15-03-51](https://user-images.githubusercontent.com/22970186/74381534-e6c90680-4da8-11ea-859a-263ff6e7f3f5.png)
> this is my configuration
> 
> ```
>   "scripts": {
>     "start": "react-app-rewired start",
>     "build": "react-app-rewired build",
>     "test": "react-app-rewired test --watchAll",
>     "eject": "react-scripts eject"
>   },
>   "husky": {
>     "hooks": {
>       "pre-commit": "pretty-quick --staged",
>       "pre-push": "npm test"
>     }
>   }
> ```

I think it's because of this line:

```
"test": "react-app-rewired test --watchAll",
```

If you change to this, it may work:

```
"test": "react-app-rewired test --watchAll=false",
```
