### ISSUE TITLE
How to run two checks ( if ) in commit-msg hook?

### ISSUE THREAD

**Issue by MenaiAla** [typicode/husky#1297] opened 2023-08-18 11:11 UTC
I have a `commit-msg` script:

```

#!/bin/sh

# This hook enforces commit messages to follow the rules

# ANSI color codes for formatting
RED='\033[0;31m'
NC='\033[0m' # No Color

commit_msg="$1"
error_msg="${RED}error: Commit message must start with a capitalized verb${NC}"
error_length_msg="${RED}error: Commit message must be more than 20 characters${NC}"

# Use regex to check if the message starts with a capitalized verb
if ! echo "$commit_msg" | grep -qE "^[A-Z][a-z]+"; then
  echo "$error_msg" >&2
  exit 1
fi

# Check the length of the commit message
if [ ${#commit_msg} -le 20 ]; then
  echo "$error_length_msg"
  exit 1
fi

```

When I do a commit message with lower letter in the begining, it executes the first check well:

```
git commit -m "test capital letter"
error: Commit message must start with a capitalized verb
husky - pre-commit hook exited with code 1 (error)
```

However, when the commit message start with capital but less than 20 letters, it stills show ( execute ) the first message:

```
git commit -m "Test 20 letters"
error: Commit message must start with a capitalized verb
husky - pre-commit hook exited with code 1 (error)

```

**Comment by typicode** [comment] 2023-09-20 20:16
Seems like a bug in the code but not sure why, sorry. Closing as the issue is old and probably fixed.

**Closed by typicode** 2023-09-20 20:16 UTC
