### ISSUE TITLE
Pre commit hooks not running in Sourcetree

### ISSUE THREAD

**Issue by jennieandersson** [typicode/husky#938] opened 2021-04-07 08:54 UTC
The pre-commit hooks works fine from the terminal, but they are not executing in Sourcetree.

OS: MacOS 11.2.3
Git: git version 2.30.1
Node: node version v12.16.1
Husky: ^6.0.0
Sourcetree version 4.0.2

Sourcetree is using git system
![Skärmavbild 2021-04-07 kl  10 52 10](https://user-images.githubusercontent.com/18212085/113838784-6b39ce00-978f-11eb-96b1-252f4ab362d2.png)

**Comment by SwerBillionaire** [comment] 2021-04-08 06:47
Did you chmodding pre-commit file to be executable? It can't be execute by default.

**Comment by jennieandersson** [comment] 2021-04-08 07:36
Yes, I've tried that. The chmod value fro the pre commit file is 755. But like I said, it's working from the terminal, but not in Sourcetree.

**Comment by xiaomeia** [comment] 2021-04-08 11:21
I have the same problem.

**Comment by natakina** [comment] 2021-04-08 14:12
The same issue with Webstorm commit dialog.
This issue seems to be a duplicate of https://github.com/typicode/husky/issues/912

**Comment by huangningfa** [comment] 2021-04-15 16:13
Change prepare script "husky install" to "husky install && echo 'PATH=$PATH:'$PATH >> .husky/_/husky.sh".

**Comment by dwjohnston** [comment] 2021-05-12 02:42
Try opening source tree from terminal

**Closed** 2021-07-18 03:37 UTC
Labels: wontfix

**Comment by Thorusan** [comment] 2022-02-16 10:27
hi,

I still have this problems. I get an error:
git -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/m_/lq68j2fd7037g2qnt0l9ysw00000gn/T/SourceTreeTemp.IGDAyn -- app/src/standard/java/org/blubblub/blubblub/ui/apisub/ApiSubscriptionActivity.kt 
fatal: cannot exec '.git/hooks/pre-commit': Operation not permitted
Completed with errors, see above
