### ISSUE TITLE
Installation with pnpm doesn't setup the hooks

### ISSUE THREAD

**Issue by eos87** [typicode/husky#61] opened 2016-08-11 16:29 UTC
Hi there, are you planning to support `pnpm` installation?

**Comment by iamstarkov** [comment] 2016-08-11 17:14
It's an issue with pnpm, not with husky

**Comment by eos87** [comment] 2016-08-11 17:15
could you please share the link to the issue (if any) just to follow up? thanks

**Comment by iamstarkov** [comment] 2016-08-12 11:55
there is no open issue relevant to yours one, so feel free to open one, do not forget to mention your platform and node, npm and pnpm versions

**Comment by iamstarkov** [comment] 2016-08-12 12:13
this issue can be closed though

**Comment by typicode** [comment] 2016-08-12 12:39
Hi @eos87,

I would also check if `pnpm` supports `npm` [install hook](https://docs.npmjs.com/misc/scripts), as this what `husky` uses to automatically install git hooks.

**Comment by iamstarkov** [comment] 2016-08-12 12:58
npm lifecycles scripts were working, were broken, now fixed, but not released yet

**Comment by zkochan** [comment] 2016-08-12 15:23
@eos87 which version of pnpm do you use? I think it should work with version 0.23 and 0.24

**Comment by iamstarkov** [comment] 2016-10-11 10:27
@eos87 ping

**Comment by zkochan** [comment] 2017-03-21 20:10
There is a new issue when using husky with pnpm and I am not sure we can fix it on the pnpm side.

Husky does not install git hooks if it detects more than 1 node_modules in the husky directory path (related code: https://github.com/typicode/husky/blob/a2da709b676fb75903922ab733d139006caf8824/src/index.js#L195)

When packages are installed with pnpm, all deps have exactly 2 node_modules in their directory path.

Related issue at pnpm: https://github.com/pnpm/pnpm/issues/669

**Comment by zkochan** [comment] 2017-09-17 18:19
I am working on a PR to husky that will fix all issues with pnpm.

**Comment by zkochan** [comment] 2017-10-29 17:38
This seems to be fixed in the beta version of husky! :tada:

**Comment by typicode** [comment] 2017-11-02 21:06
Happy to support a project like pnpm ;)

2017-10-29 18:38 GMT+01:00 Zoltan Kochan <notifications@github.com>:

**Comment by iamstarkov** [comment] 2017-11-29 21:08
this is awesome. was it released?

**Comment by zkochan** [comment] 2018-05-12 16:28
@typicode, from version 1.0.0-rc.3 husky doesn't work with pnpm. 

it always prints: `Trying to install from node_modules directory, skipping Git hooks installation.`

it did work in v1.0.0-rc.2

**Comment by typicode** [comment] 2018-05-14 01:55
@zkochan thanks for the heads up, I'm reproducing it. I'm having a look.

**Comment by typicode** [comment] 2018-05-14 22:00
`v1.0.0-rc.6` should fix it, and I've added a `pnpm` test (https://github.com/typicode/husky/blob/dev/src/installer/__tests__/index.ts#L73)

**Comment by zkochan** [comment] 2018-05-15 00:00
@typicode thanks! Finally, I was able to add husky to the pnpm repo https://github.com/pnpm/pnpm/commit/bd38fb50b548f3df1a05ff48fae208b268ecdde5

**Comment by typicode** [comment] 2018-05-15 00:16
@zkochan 😃 🎉

**Closed** 2018-05-17 22:26 UTC
