### ISSUE TITLE
cannot install node on CI in docker container

### ISSUE THREAD

**Issue by vidavidorra** [typicode/husky#493] opened 2019-05-26 18:31 UTC
I can't seem to install husky on shippable CI inside a custom docker container. I get the following error message. I'm not sure whether this issue is actually related to husky or npm so thought to check here first. I've seen similar issues here but not resolving my issue. I have husky installed as a dep dependency but in these logs have removed that and am just running the husky install. This is on Ubuntu 14.04 BTW. The weird thing is that when I have the run the docker container (`vidavidorra/docker-linux:ubuntu1404-master`) locally and try to install, husky installs without problems.

```
$ npm --version
6.9.0

$ node --version
v12.1.0

$ npm i -D husky@latest

> husky@2.3.0 install /root/src/github.com/vidavidorra/ci-fiddle/node_modules/husky
> node husky install

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '/root/src/github.com/vidavidorra/ci-fiddle/node_modules/husky/husky'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@2.3.0 install: `node husky install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the husky@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-26T09_32_34_233Z-debug.log
```
Full logs [here](https://app.shippable.com/github/vidavidorra/ci-fiddle/runs/36/1/console).

**Comment by typicode** [comment] 2019-06-05 16:02
Hi @vidavidorra,

I've seen it already, but not sure why it's happening. Husky isn't doing anything particular during the install, so I would tend to think it's related to npm under certain conditions (or maybe it's not that at all).

Do you need to have git hooks it in the CI?

By default, husky checks if it's running in a CI and doesn't install if that's the case.

**Comment by vidavidorra** [comment] 2019-06-05 17:28
@typicode Thanks for your reaction.

> Do you need to have git hooks it in the CI?

Not at all actually. In the OP I installed it manually, but just having it as a dependency in the _package.json_ it fails with the same error. See the log [here](https://app.shippable.com/github/vidavidorra/ci-fiddle/runs/46/1/console).

> By default, husky checks if it's running in a CI and doesn't install if that's the case.

Could it maybe be failing to do so on the CI I'm using? I use a custom docker container on Shippable CI as written in the OP, but get successful installation locally on the exact same container.
I actually tried to manually check whether husky can detect whether it is a CI environment `node ./node_modules/is-ci/bin.js && echo "This is a CI server"` and it detected it successfully (see log [here](https://app.shippable.com/github/vidavidorra/ci-fiddle/runs/45/1/console)). Could it be that husky is still trying to install?

**Comment by anodalncl** [comment] 2019-07-16 14:32
Any answer fo this?

**Comment by RobertLowe** [comment] 2020-05-04 22:05
I saw this issue as well and have located the root cause. Which is... `root`, something about being root user cause this to fail

**Comment by komanton** [comment] 2020-08-11 09:55
Any updates? the same issue in docker container https://github.com/microsoft/vscode-dev-containers/tree/v0.112.0/containers/javascript-node-10

**Comment by typicode** [comment] 2021-04-03 11:02
Closing as v6 works differently and to clean older issues. Feel free to create a new one if needed.

**Closed** 2021-04-03 11:01 UTC
