### ISSUE TITLE
Broken stdout format logs lint-staged

### ISSUE THREAD

**Issue by acidcrash2005** [typicode/husky#1134] opened 2022-04-22 12:14 UTC
**Troubleshoot**
Very strange but broken stdout logs when husky run  lint-staged. 

now
<img width="690" alt="image" src="https://user-images.githubusercontent.com/11617578/164710534-b39df47c-8d1a-4585-b16b-050b229980fb.png">

must be:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/11617578/164710668-fc0cdae4-7800-4e50-b7cd-37e8abeb3319.png">

**Context**
Please describe your issue and provide some context:
- terminal zsh

**Comment by typicode** [comment] 2022-04-26 05:58
Duplicate of #968

**Closed** 2022-07-02 21:55 UTC
Labels: help wanted, wontfix
