### ISSUE TITLE
Husky doesn't remove deprecated shebang and husky script from commit-msg hook (breaking change in 9.1.1)

### ISSUE THREAD

**Issue by maksnester** [typicode/husky#1476] opened 2024-07-23 11:01 UTC
**Context**

-  "husky": "9.1.1",
- git version 2.39.3 (Apple Git-146)

I have 2 git hooks in my project:
* commit-msg
* pre-commit

When "husky" command gets executed it removes this code

```
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
```

from `pre-commit` hook, but not from the `commit-msg` and apparently it makes `commit-msg` to be skipped completely which is a breaking change in 9.1.**1**

**Comment by typicode** [comment] 2024-07-24 10:42
I can't reproduce the issue. I've created a `pre-commit` and `commit-msg` and it gets replaced in both 🤔

**Comment by GuiguiBlitz** [comment] 2024-07-25 08:02
Hello, i have a similar issue, where husky install leaves unstaged changes on the checked out repo. Reverting back to 9.0.11 fixes my ci issue.

**Comment by jan-molak** [comment] 2024-07-25 11:39
> I can't reproduce the issue. I've created a `pre-commit` and `commit-msg` and it gets replaced in both 🤔

Hey @typicode, I noticed the issue after upgrading Husky from 9.0.11 to 9.1.1 by [merging an update](https://github.com/serenity-js/serenity-js/actions/runs/10092563626/job/27907340786) proposed by Renovate:

```
lerna ERR! Error: Command failed with exit code 1: git commit -F /tmp/430e22ec-409b-43d7-b05b-3ce9afd364fc/lerna-commit.txt
lerna ERR! .husky/_/commit-msg: 2: .: cannot open .husky/_/_/husky.sh: No such file
lerna ERR! husky - commit-msg script failed (code 2)
lerna ERR!     at makeError (/home/runner/work/serenity-js/serenity-js/node_modules/@lerna/child-process/node_modules/execa/lib/error.js:60:11)
lerna ERR!     at handlePromise (/home/runner/work/serenity-js/serenity-js/node_modules/@lerna/child-process/node_modules/execa/index.js:118:26)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! Error: Command failed with exit code 1: git commit -F /tmp/430e22ec-409b-43d7-b05b-3ce9afd364fc/lerna-commit.txt
lerna ERR! .husky/_/commit-msg: 2: .: cannot open .husky/_/_/husky.sh: No such file
lerna ERR! husky - commit-msg script failed (code 2)
lerna ERR!     at makeError (/home/runner/work/serenity-js/serenity-js/node_modules/@lerna/child-process/node_modules/execa/lib/error.js:60:11)
lerna ERR!     at handlePromise (/home/runner/work/serenity-js/serenity-js/node_modules/@lerna/child-process/node_modules/execa/index.js:118:26)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna Command failed with exit code 1: git commit -F /tmp/430e22ec-409b-43d7-b05b-3ce9afd364fc/lerna-commit.txt
lerna ERR! lerna .husky/_/commit-msg: 2: .: cannot open .husky/_/_/husky.sh: No such file
lerna ERR! lerna husky - commit-msg script failed (code 2)
```

My `.husky/commit-msg` file:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit "${1}"
```

Do I understand your instructions correctly that in order to use Husky 9.1.1 we should remove the below lines:
```diff
- #!/bin/sh
- . "$(dirname "$0")/_/husky.sh"
-
npx --no -- commitlint --edit "${1}"
```

Could it be that Husky is trying to migrate the scripts when it's executed manually on a dev's machine, but the migration is not triggered when the update to Husky is brought in via a pull request from a tool like Renovate?

**Comment by typicode** [comment] 2024-07-25 13:14
> but the migration is not triggered when the update to Husky is brought in via a pull request from a tool like Renovate?

That seems so. It's something that I didn't expect would cause issues so I reverted this behavior in `v9.1.2`. Only a message will be shown.

You can still have them in `v9.1.1`, but hooks will fail in `v10.0.0` so better remove these lines when you have the time.

Sorry everyone for the trouble.

**Comment by typicode** [comment] 2024-08-01 10:13
Closing since v9.1.4 doesn't try to remove them anymore but instead shows a message

**Closed by typicode** 2024-08-01 10:13 UTC
