### ISSUE TITLE
support interactive prompt in git hooks

### ISSUE THREAD

**Issue by foisonocean** [typicode/husky#249] opened 2018-03-08 12:37 UTC
My problem is almost the same as [this](https://stackoverflow.com/questions/3417896/how-do-i-prompt-the-user-from-within-a-commit-msg-hook), could you consider support that?

**Comment by jesstelford** [comment] 2018-04-17 08:08
Possible duplicate of https://github.com/typicode/husky/pull/166

**Comment by foisonocean** [comment] 2018-04-17 09:08
@jesstelford  Any updates for your PR? I'm really need this feature.

**Comment by jesstelford** [comment] 2018-04-18 01:39
Your best bet is probably to fork it and merge my changes into your fork. There was an impasse for GUI applications blocking that PR :(

**Closed** 2018-04-27 06:12 UTC
