### ISSUE TITLE
v5 - Documentation for the content of the .husky subfolder - line ending changes unpredictably for .husky.sh / .gitignore

### ISSUE THREAD

**Issue by JanFellner** [typicode/husky#905] opened 2021-03-19 14:00 UTC
Hi,

is there a documentation of the possible files in the .husky subfolder and how to deal with em?
In the documentation i could find doc for the pre and post files but not for suplemental files which somewho appear in that folder.

.husky/.gitignore
.husky/_/husky.sh

So as the files were there i commited them and now notice that those files are touched almost every time i check them out on different systems. (Always with different line endings... / I work on windows on all the system i check them out)

* What are they for
* Are they ment to be checked in or ignored
* If those are config files whom is rewriting them and for what purpose

I expected .husky to be a config folder and that the files in there are only overwritten or changed if not there on installation or dedicated request but it looks they are written "randomly".

The files change after **npm ci** having "postinstall": "husky install" in the package.json

Jan

**Comment by typicode** [comment] 2021-03-21 16:48
Hi @JanFellner,

You can view husky.sh as a small wrapper to run hooks. It's generated by husky and shouldn't be modified.
`.husky/.gitignore` is meant to be checked (it will actually make git ignore `.husky/_/` directory).

They're rewritten when `husky install` is run.

By the way, it's now recommended to use `prepare` instead of `postinstall` if you're using `npm` (you can also remove `pinst`). See docs for updated instructions.

Regarding the line endings, husky always add a `\n` at the end. The change in line endings may be due to some Git config/OS 
 (Windows) related things.

**Comment by JanFellner** [comment] 2021-03-22 09:02
Hi @typicode,

we use the suggested git config (since years) that holds the files stored with LF and checks them out platform specific, on windows CRLF. (occasionally we define rules for specific files if we need to have them CRLF or LF on all platforms using the gitattributes).

So we have the config 
`
C:\Windows\System32>git config core.autocrlf
true
`

That somehow conflicts now with how husky is doing it. (If husky is writing those files anyway on every install i don´t understand why they are placed in a config folder)

I will ignore both files in the root gitignore for all affected projects but i guess other windows developers might face the same issue.

(Concerning the npm postinstall vs prepare, we will switch to yarn in one of the next sprints, so i will currently keep it as it looks like with yarn 2 you need to use postinstall anyway. Yarn is just faster cause an npm ci takes 2 minutes with all the dependencies we now have :\, for the ones with a poor internet connection even worse...)

Jan

**Comment by typicode** [comment] 2021-03-23 06:00
I'll do some more tests on Windows. Thanks for the details! :+1: 
Any recommended steps to reproduce the issue?

> yarn 2 you need to use postinstall anyway

True

**Comment by JanFellner** [comment] 2021-03-25 11:45
If you do the following you can simply see the issue:

Set git config core.autocrlf 
npm i husky
npx husky install (files are added with \n)
git commit the husky folder
delete the folder on disk
revert the deletion (git creates the files with \r\n) <- (files are not modified for git due to autocrlf rule)

commit the files with \r\n
delete the folder on disk
revert the deletion (no modified files)
npx husky install <- modified files

**Comment by SalahAdDin** [comment] 2021-04-10 21:46
Is there any big change between these and the sixth version?

**Comment by CaioCSdev** [comment] 2021-04-28 17:10
Hi,
About the missing documentation that the files under `.husky/` should be checked, except under `.husky/_/`.

I could create a PR adding that :smiley: . Is it okay?

**Comment by typicode** [comment] 2021-07-01 05:31
Line endings issue is fixed in v7. You can delete `.husky/.gitignore` :+1:

**Closed by typicode** 2021-07-01 05:31 UTC
