### ISSUE TITLE
[Windows 10]: Husky can't find npx in path unless the command is run at least once

### ISSUE THREAD

**Issue by G-Rath** [typicode/husky#659] opened 2020-01-26 03:06 UTC
Before creating an issue, see [troubleshoot](https://github.com/typicode/husky#troubleshoot) section in the README and verify that you're using Git `>= 2.13.0`.

Please provide your OS, terminal and the following commands output:

Windows 10, WSL/GUI

```sh
C:\Users\G-Rath\workspace\projects-ackama\eslint-config-ackama>git commit
husky:debug husky v4.2.1 - pre-commit
husky:debug Current working directory is /c/Users/G-Rath/workspace/projects-ackama/eslint-config-ackama
husky:debug source ~/.huskyrc
Can't find npx in PATH: /mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/G-Rath/bin:/c/Users/G-Rath/workspace/projects-ackama/eslint-config-ackama/node_modules/.bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/
c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/bin:/cmd:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Users/G-Rath/AppData/Local/Microsoft/WindowsApps:/c/Users/G-Rath/AppData/Local/hyper/app-3.0.2/resources/bin:/c/Program Files/JetBrains/IntelliJ IDEA 2019.3.1/bin
Skipping pre-commit hook
```

This is a bit of an interesting one, which ideally it would be great if husky supported, but I'm not sure what the actual best fix is.

In a nutshell I've decided to forgo installing anything on my Windows host local-dev commandline wise, instead working purely in WSL.

This is what I was almost doing on my last laptop, except WSL came after I'd gotten it and so things like `node` were already installed, but I decided to just install things in WSL and see when/if I got blocked by something that I couldn't get to use WSL.

Anyway, this worked fine for husky 3, but for husky 4 it doesn't because npx can't be found.

Previously husky 3 was using `run_node`, which worked b/c I can call node using a script located in `C:\bin` (which does exist on PATH) like so:

```
# windows shim of node that is called by run_node

cmd '/C C:\Users\G-Rath\AppData\Local\Microsoft\WindowsApps\ubuntu.exe run "/home/g-rath/.nodenv/shims/node"' $@
```

The above script is called `node`, and it works fine for `npx` too by just replacing `node` with `npx`.
This also means I can call `npx` & `node` in "Git for Windows", which serves as a POC that it works.

However, for some reason it doesn't work entirely same in huskys git commit script: While *I can call npx*, `command -v "$1" >/dev/null 2>&1` will return `1` *until npx is invoked and thus hashed*.

The solution I've found is that I can just stick `npx --version` in `.huskyrc`, but I can't for the life of me figure out what's actually causing the problem: as I said above:

  * `npx` works fine when called manually via MINGW64 (as provided by Git for Windows)
    * including `command -v "$1" >/dev/null 2>&1`
  * any attempt to "find" `npx` before it's called fail, except for actually calling it - once called everything else then works fine.
  * `/c/bin` is included in the path
  * `run_node` was fine with it.

------

In saying all of the above, I don't think this is anything new, rather than it's that `run_node` was doing something, as I see in husky 3:

```
  if ! command -v node >/dev/null 2>&1; then
    echo "Info: can't find node in PATH, trying to find a node binary on your system"
  fi
```

Which I saw everytime.

All in all, I've got a workaround, but am interested in spitballing possible causes :)

**Comment by brettz9** [comment] 2020-05-18 02:42
Dupe of #639 ?

**Comment by typicode** [comment] 2021-04-03 11:04
Sorry to not be able to help. I'm not sure why it's happening.
I hope it has been fixed since then.

**Closed by typicode** 2021-04-03 11:04 UTC
