### ISSUE TITLE
Husky failed to install with `Cannot read property 'toString' of null` message.

### ISSUE THREAD

**Issue by panosangelopoulos** [typicode/husky#655] opened 2020-01-21 16:04 UTC
OS: MacOS 10.15.2 (19C57)
Git: git version 2.23.0

❯ node -v
v12.14.0

```
"husky": "^4.0.6",
```
During the installation i'm getting the following error.

```sh
husky > Setting up git hooks 
Cannot read property 'toString' of null 
husky > Failed to install
```

**Comment by typicode** [comment] 2020-01-21 21:06
Thanks for the report, could you try with `HUSKY_DEBUG=1` and `v4.1.0`?

**Comment by scottwhite** [comment] 2020-01-28 13:44
Had the same error.
I run in a docker container (project files are on a shared volume).  I have no git in the container, this is what I get with HUSKY_DEBUG=1

`husky > Setting up git hooks
husky:debug Current working directory is /opt/app/node_modules/husky
Cannot read property 'toString' of null
husky:debug TypeError: Cannot read property 'toString' of null
    at Object.checkGitVersion (/opt/app/node_modules/husky/lib/installer/checkGitVersion.js:12:32)
    at run (/opt/app/node_modules/husky/lib/installer/bin.js:60:31)
    at Object.<anonymous> (/opt/app/node_modules/husky/lib/installer/bin.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/app/node_modules/husky/husky.js:20:3)
husky > Failed to install
`

Installing git into the container fixed this issue.

**Comment by th3oxen** [comment] 2020-02-25 11:22
I had the same issue with Windows 7 on local machine. The problem was that I did not have git registered as a PATH variable. Adding `path\to\Git\bin` solved the problem.

**Comment by DavidRimar** [comment] 2020-09-05 10:46
Hi,

Could anyone please shed light on **what husky is referring to** when it says "Cannot read property 'toString' of null"? Would this be the pre-commit file in the .git/hooks folder?

I have the same issue, have tried troubleshooting this for a while. 

OS: Windows 10
Git: git version 2.28.0
node -v
v12.16.1

(1 Git is registered as a PATH variable
(2 Have tried installing/uninstalling Husky
(3 Have tried deleting .git/hooks/pre-commit file / making it executable

THE MAIN ISSUE:
The pre-commit file is not being modified with Husky code! The installation message:

husky > Setting up git hooks 
Cannot read property 'toString' of null 
husky > Failed to install

Thanks for any help!

**Comment by johnico** [comment] 2020-11-02 08:14
happened to me also. 
happens only during docker container build 

```
> husky@4.3.0 install /opt/web/node_modules/husky
> node husky install

husky > Setting up git hooks
Cannot read property 'toString' of null
husky > Failed to install
```

tried to use version 2.6.0 and got this error

```
husky > Setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.
```
the .git is in the dockerignore . i also tried to remove it from there 


how can I fix it ?

**Comment by Hongbo-Miao** [comment] 2020-12-05 15:37
Got same error after updating from 4.3.0 to 4.3.4
It happens both when I try to build in Heroku, and also in a Docker.

**Comment by Divlo** [comment] 2020-12-05 21:18
Indeed, I also revert back to `husky@4.3.0` while waiting for a fix.

**Comment by typicode** [comment] 2020-12-05 23:49
@Hongbo-Miao do you know the npm version that was used?

**Comment by rkrn** [comment] 2020-12-06 07:39
Also experienced this today. Reverting to `husky@4.3.0` for now.

```
> node husky install
husky > Setting up git hooks
Cannot read property 'toString' of null
husky > Failed to install
```

**Comment by Divlo** [comment] 2020-12-06 10:07
Duplicate of #821 
https://github.com/typicode/husky/issues/821#issuecomment-739430917

**Comment by Hongbo-Miao** [comment] 2020-12-06 20:26
For me, I ended up with upgrading to Husky 5.0.4
And the Husky docs are well-written! These two parts help:

- https://typicode.github.io/husky/#/?id=bypass-hooks
- https://typicode.github.io/husky/#/?id=disable-hooks-in-ci

**Comment by jenskuhrjorgensen** [comment] 2021-01-04 08:04
> Duplicate of #821
> [#821 (comment)](https://github.com/typicode/husky/issues/821#issuecomment-739430917)

As far as I can see, the fix in the issue you linked is to install version 4.3.6. I'm already on that version and I'm still experiencing this issue.

**Comment by jenskuhrjorgensen** [comment] 2021-01-04 08:12
Hi @typicode 

This issue seems to have been around for quite some time, but has lately received some traction. Do you have a comment on how to fix this? 

Best regards
Jens

**Comment by typicode** [comment] 2021-01-11 03:19
Hi @jenskuhrjorgensen,

Which version of npm are you using? If you're on npm 7, could you retry with the latest version?

**Comment by jenskuhrjorgensen** [comment] 2021-01-11 07:57
@typicode 

I'm not on version 7 yet. I'm running `6.14.10`.

It is worth noting, that Husky actually works as expected in my local environment, but it clutters my CI logs with the aforementioned error. [The documentation](https://github.com/typicode/husky/tree/master#ci-servers) says that Husky should not even be installed on CI by default, but it appears to try.

**Comment by typicode** [comment] 2021-01-11 23:09
And what's the package manager version on the CI?

**Comment by jenskuhrjorgensen** [comment] 2021-01-12 06:43
@typicode

It is the CI that is running npm v `6.14.10`.

**Comment by typicode** [comment] 2021-01-15 23:16
Could you retry with husky `v4.3.8`?

**Comment by jenskuhrjorgensen** [comment] 2021-01-17 15:25
@typicode

With 4.3.8 I'm get ting `git --version command failed. Got null` instead.

**Comment by typicode** [comment] 2021-01-23 02:01
@jenskuhrjorgensen Thanks for the detail.

Git version check happens before checking if husky is running in CI, that's why the error is displayed.

I feel It would be a bit complicated to improve that in v4 without changing install logic and maybe introducing unexpected bugs. Maybe if I have time later.

Also, besides `git` command not available in CI, I don't see why `git --version` fails.

As a workaround, you could prevent husky from installing (and this error message) by setting `HUSKY_SKIP_INSTALL=1` environment variable.

**Comment by jenskuhrjorgensen** [comment] 2021-01-23 07:45
Hi @typicode

It might happen because I don't have `git` installed in some of the Docker images that my CI uses. `node:10-slim` for instance. So if the `git` version check is part of husky, maybe do it after checking if husky should be installed at all (`isCI`).

**Comment by typicode** [comment] 2021-04-03 11:06
Husky 6 is now MIT again. I'd recommend upgrading to fix this issue.
Feel free to create a new one if needed :+1:

**Closed by typicode** 2021-04-03 11:06 UTC
Labels: bug
