### ISSUE TITLE
Does not install git hooks when using yarn

### ISSUE THREAD

**Issue by Jflinchum** [typicode/husky#84] opened 2016-12-12 17:06 UTC
When running `yarn add husky --dev`, the git hooks do not get set up. I have to run the install script manually, and then it works fine.

Yarn version: `0.17.9`

**Comment by SxMShaDoW** [comment] 2016-12-12 17:12
👍 on this functionality.

**Comment by typicode** [comment] 2016-12-12 17:58
Thanks for the feedback.
Seems it does run husky's `postinstall` just once, except if you ignore cache by using `--force`.

```sh
/tmp$ rm .git/hooks/pre-commit
rm: cannot remove '.git/hooks/pre-commit': No such file or directory
/tmp$ yarn add --dev husky 
yarn add v0.17.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ husky@0.11.9
Done in 0.14s.
/tmp$ cat .git/hooks/pre-commit
cat: .git/hooks/pre-commit: No such file or directory
/tmp$ yarn add --dev husky --force
yarn add v0.17.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ husky@0.11.9
Done in 0.75s.
/tmp$ cat .git/hooks/pre-commit
#!/bin/sh
# husky
cd .
...
```

**Comment by avaly** [comment] 2017-02-15 13:02
Can this be addressed in a future version? Projects and teams using `yarn` should not need to manually run the `--force` command in order to get the functionality working.

**Comment by typicode** [comment] 2017-02-15 14:48
Hi @avaly,

Yes it will.
I have a few ideas for this but need to do some testing.

**Comment by elektronik2k5** [comment] 2017-02-25 07:56
I've encountered a few issues with it too :(. Had to remove the hook manually from `.git/hooks/` then `yarn add husky --dev --force` to make it work.

**Comment by ahstro** [comment] 2017-03-13 10:44
I'm not experiencing this. Is it fixed? If so, close? :)

**Comment by cs-miller** [comment] 2017-05-09 01:31
still experiencing this

**Comment by erquhart** [comment] 2017-05-17 14:32
@typicode is this still in the works?

**Comment by typicode** [comment] 2017-05-17 21:13
@erquhart it seems to have been solved by `yarn` `v0.24.5`

**Closed** 2017-05-21 13:36 UTC

**Comment by evenfrost** [comment] 2017-05-24 14:32
Just faced the same problem with yarn v0.24.5, same with fresh yarn cache (i.e. after`yarn cache clean'). Only `yarn add --dev husky --force` helps.

Can be reproduced on my [booted](https://github.com/evenfrost/booted).

**Comment by typicode** [comment] 2017-05-28 17:31
Hi @evenfrost,

Here's what I did to test:

```sh
/tmp$ mkdir A
/tmp$ cd A
/tmp/A$ git init && yarn init -y && yarn add husky --dev
Initialized empty Git repository in /private/tmp/A/.git/
yarn init v0.24.5
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
✨  Done in 0.07s.
yarn add v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 12 new dependencies.
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ chalk@1.1.3
├─ ci-info@1.0.0
├─ escape-string-regexp@1.0.5
├─ find-parent-dir@0.3.0
├─ has-ansi@2.0.0
├─ husky@0.13.4
├─ is-ci@1.0.10
├─ normalize-path@1.0.0
├─ strip-ansi@3.0.1
└─ supports-color@2.0.0
✨  Done in 0.86s.
/tmp/A$ cat .git/hooks/pre-commit
#!/bin/sh
#husky 0.13.4
# ...

/tmp/A$ cd ..
/tmp$ mkdir B
/tmp$ cd B
/tmp/B$ git init && yarn init -y && yarn add husky --dev
Initialized empty Git repository in /private/tmp/B/.git/
yarn init v0.24.5
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
✨  Done in 0.07s.
yarn add v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 12 new dependencies.
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ chalk@1.1.3
├─ ci-info@1.0.0
├─ escape-string-regexp@1.0.5
├─ find-parent-dir@0.3.0
├─ has-ansi@2.0.0
├─ husky@0.13.4
├─ is-ci@1.0.10
├─ normalize-path@1.0.0
├─ strip-ansi@3.0.1
└─ supports-color@2.0.0
✨  Done in 0.78s.
/tmp/B$ cat .git/hooks/pre-commit
#!/bin/sh
#husky 0.13.4
# ...

```

I was able to make `booted` work with `husky` this way (git needs to be initialized first in the target directory):

```sh
/tmp$ mkdir booted-test
/tmp$ cd booted-test/
/tmp/booted-test$ git init
Initialized empty Git repository in /private/tmp/booted-test/.git/
/tmp/booted-test$ cd ..
/tmp$ ./node_modules/.bin/booted booted-test/
 ✔ Copying code...
 ✔ Installing packages with Yarn...
 ✔ Booted.
/tmp$ cd booted-test/
/tmp/booted-test$ cat .git/hooks/pre-commit
#!/bin/sh
#husky 0.13.3
# ...
```

**Comment by evenfrost** [comment] 2017-05-29 10:04
Hmm weird, can confirm reproducing these steps manually fixed the issue for me. Will investigate my package workflow further, thanks @typicode.

**Comment by hammadzz** [comment] 2017-10-26 19:56
I am encountering the same issue on yarn 0.27.5

**Comment by philihp** [comment] 2018-09-20 21:33
@typicode Encountering this again.

Yarn 1.9.4
npm 6.4.1
node v8.11.4
husky1.0.0-rc.14

To get around this and force it, I added to my package.json's scripts:
```
  "postinstall": "node ./node_modules/husky/lib/installer/bin install"
```

**Comment by hjemmel** [comment] 2019-02-13 17:43
Same problem here using 1.13.0 and latest version of husky

**Comment by eduardoarandah** [comment] 2019-12-11 17:40
So google can find it for the next guy: 


# husky hooks not working manually install

Execute this in your command line: 

```
node ./node_modules/husky/lib/installer/bin install
```

**Comment by Nikodermus** [comment] 2020-02-21 01:18
Why is this closed? The actual issue is not solve
Still happening in 1.22.0

**Comment by technoknol** [comment] 2020-03-14 10:15
For me it was git version. I've updated git version and it worked like charm. Make sure your `git` is `> 2.13`

**Comment by lucadegasperi** [comment] 2020-04-01 13:12
Getting the same issue as @Nikodermus here's my setup:

```
yarn 1.22.4
node 12.16.0
husky ^4.2.3
```

**Comment by allenGKC** [comment] 2020-04-23 05:37
> Why is this closed? The actual **_issue is not solved_**, is **still happening** in:
> 
> ```
> yarn 1.22.0
> node v13.7.0
> husky ^4.2.3
> ```
> 
> When I try to run the above command, it fails:
> 
> ```
> node ./node_modules/husky/lib/installer/bin install
> husky > Setting up git hooks
> Cannot destructure property 'name' of 'which_pm_runs_1.default(...)' as it is undefined.
> husky > Failed to install
> ```
> 
> Removing `.git/hooks` didn't work either, neither **_adding it as a postinstall_** script did

@Nikodermus  Have you solved this problem?

**Comment by allenGKC** [comment] 2020-04-23 06:12
@Nikodermus  try this method https://github.com/typicode/husky/issues/640#issuecomment-578893362

**Comment by Norserium** [comment] 2020-05-20 14:44
Installing the last Yarn version (1.22.4) and running command `yarn add --dev husky --force` solved this problem for me.

**Comment by cat-walk** [comment] 2020-08-11 10:14
> Why is this closed? The actual **_issue is not solved_**, is **still happening** in:
> 
> ```
> yarn 1.22.0
> node v13.7.0
> husky ^4.2.3
> ```
> 
> When I try to run the above command, it fails:
> 
> ```
> node ./node_modules/husky/lib/installer/bin install
> husky > Setting up git hooks
> Cannot destructure property 'name' of 'which_pm_runs_1.default(...)' as it is undefined.
> husky > Failed to install
> ```
> 
> Removing `.git/hooks` didn't work either, neither **_adding it as a postinstall_** script did

using the version '3.1.0' solved my problem.
```
    "husky": "^3.1.0",
```

**Comment by AndreaCitrolo** [comment] 2020-10-14 08:31
@cat-walk you are experiencing that issue because you are not running that command through yarn so the script cannot infer your package manager name, the error is not very explicative in this case. Try adding:

```javascipt
    "setuphusky": "node ./node_modules/husky/husky.js install"
```
to your package json and then run: 
```shell
yarn run setuphusky
```

**Comment by rossthedevigner** [comment] 2020-11-17 23:19
At version 5 (husky@latest) and I don't get the manual install either. Only on ^4.3.1

**Comment by kabaros** [comment] 2020-11-26 18:06
for anyone having this issue (which seems to also happen with `npm 7`), the solution for me was to run ` INIT_CWD=.git/hooks node ./node_modules/husky/lib/installer/bin.js install` to force installing the hooks under `.git/hooks`

**Comment by Xunnamius** [comment] 2020-11-27 23:26
Just chiming in to say I'm experiencing this as well with `husky@4`... on `npm 7`, as @kabaros alluded to. The only solution that worked for me was to upgrade to `husky@5` and add `"postinstall": "if [ -z \"$CI\" ]; then husky install; else echo 'skipped installing husky git hooks'; fi"` to my package.json (instead of pinst).

**Comment by matsad3547** [comment] 2021-02-12 21:26
I'm still having this issue: 
```
yarn 1.22.5
node v14.12.0
husky ^5.0.9
```
after running `yarn add --dev husky --force` and `cat .git/hooks/pre-commit` I've still got `cat: .git/hooks/pre-commit: No such file or directory`

I've also tried running `install.js` directly from the command line via `node ./node_modules/husky/lib/commands/install` but that didn't work either.  That's how the `husky` package is now structured; the above command errored for me.

**Comment by chenasraf** [comment] 2021-02-18 16:08
The hooks won't get created for me either.

```
node 14.15.4
yarn 1.22.10
husky 5.0.9
```

The hooks won't run, install says it's successful but it doesn't create any hooks.

```
node_modules/.bin/husky install     
husky - Git hooks installed
```

But when I commit, it immediately proceeds without running anything.

package.json:

```
  "husky": {
    "hooks": {
      "pre-commit": "echo 'RUNNING HOOK!'"
    }
  }
```

**Comment by johnhayesio** [comment] 2021-02-19 12:07
Same issue I have. I have removed and re-added husky without any change. I have also run the install file directly, but this doesn't do anything either. My versions are as follows:
```
node 14.15.2
yarn 1.22.10
husky 5.0.9
```
Same issues as @chenasraf .

**Comment by chenasraf** [comment] 2021-02-19 13:34
Turns out husky v5 **does not** pull hooks from package.json anymore. You **have** to use `husky add [hook-name] [command]`

In my opinion, that's worse as it pollutes the tree with another set of plain script files, which contain the command itself, instead of abstracting the command into the runner itself... Also husky add doesn't always chmod the file properly, so it's more steps to make hooks work, plus they're uglier now.

**Comment by matsad3547** [comment] 2021-02-19 21:15
@chenasraf Doh!  Missed that, thanks for pointing it out.

**Comment by lauthieb** [comment] 2021-02-21 23:29
> The hooks won't get created for me either.
> 
> ```
> node 14.15.4
> yarn 1.22.10
> husky 5.0.9
> ```
> 
> The hooks won't run, install says it's successful but it doesn't create any hooks.
> 
> ```
> node_modules/.bin/husky install     
> husky - Git hooks installed
> ```
> 
> But when I commit, it immediately proceeds without running anything.
> 
> package.json:
> 
> ```
>   "husky": {
>     "hooks": {
>       "pre-commit": "echo 'RUNNING HOOK!'"
>     }
>   }
> ```

Same for us on https://github.com/decathlon/vitamin-web

**Comment by typicode** [comment] 2021-02-22 19:58
Hi,

husky 5  has a breaking change regarding config, .huskyrc isn’t supported anymore. See docs for install or migration steps.

**Comment by lauthieb** [comment] 2021-02-23 00:04
@typicode indeed, thanks!
Fixed: https://github.com/Decathlon/vitamin-web/commit/29e3ef772b11e3c20491911817ef71acdd8c539a
:tada:

**Comment by Noah-Krossa** [comment] 2021-02-28 10:37
Try to exe ```npx husky install``` before install husky like dev dependencie, this command substitute default git hooks by husky hooks.

**Comment by jasan-s** [comment] 2021-03-20 05:28
using `yarn --force` also worked for me

**Comment by srgg** [comment] 2021-03-25 08:26
I've spent a lot of time trying to figure out what is wrong, but the things are that they have changed the entire approach. For those who are still struggling with this issue, and for newcomers  read this manual https://blog.typicode.com/husky-5/ section "Optional install".

dammit..

**Comment by chenasraf** [comment] 2021-03-25 08:29
Genuinely confused about the decision to remove support for config files, you could always link to your own scripts before, but now your are much more limited...

**Comment by LuisValgoi** [comment] 2021-05-27 17:05
Fixed through: 

```js
  "scripts": {
    "postinstall": "node ./node_modules/husky/lib/bin install",
    "dev": "craco start",
    "build": "craco build",
    ...
  },
   ...
  "devDependencies": {
    ...
    "husky": "^6.0.0",
    ...
  },
```

![image](https://user-images.githubusercontent.com/8363610/119867712-9077cc80-bef4-11eb-80f3-3920ff1cd45e.png)
