### ISSUE TITLE
Does not work with Github Desktop on Windows

### ISSUE THREAD

**Issue by ZhaoXiangXML** [typicode/husky#1163] opened 2022-06-16 08:11 UTC
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

If you're migrating from husky 4, see:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

**Context**
Please describe your issue and provide some context:

I've this pre-commit hook:
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
```

It works with git command line and Tortoise Git on Windows as expected, but on Github Desktop 3.0.2 I've this error message when I commit:
```
An address incompatible with the requested protocol was used.

husky - pre-commit hook exited with code 1 (error)
```

A hook file like this works:
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo hello
```

But anything with `npm` does not.

Please kindly check it out.

Thank you!

**Comment by ZhaoXiangXML** [comment] 2022-06-16 08:17
Steps to reproduce:

In an empty folder:
1. `git init`
2. Save this file as `package.json`
```json
{
    "scripts": {
        "prepare": "husky install",
        "test": "echo hello"
    },
    "devDependencies":{
        "husky": "^8.0.1"
    }
}
```
3. `npm install`
4. `npx husky add .husky/pre-commit "npm test"`
5. Open the folder in Github Desktop and try to commit it
![image](https://user-images.githubusercontent.com/719497/174025471-2780d87b-180c-4543-8db9-1d4858eb4f1f.png)

**Comment by Jonathan939** [comment] 2022-07-29 22:15
I am having the same issue, but on Github Desktop 3.0.5 the first line of the error doesn't show up:
![image](https://user-images.githubusercontent.com/16197931/181852461-04c3446e-4129-4402-a09d-e1472f005ed1.png)

**Comment by tuchk4** [comment] 2022-09-06 00:08
I can confirm it doesn't work with Github Desktop, while it works from the terminal
<img width="449" alt="image" src="https://user-images.githubusercontent.com/5140611/188522470-546be28b-3727-4919-9d8a-0c9de0b5f287.png">

**Comment by DoctorDerek** [comment] 2022-09-07 20:04
Adding "C:\Program Files\Git\bin" to my PATH environment variable fixed this error at one point, [as I described on Stackoverflow](https://stackoverflow.com/a/67132704/2167762). Maybe try that?

**Comment by ThenTech** [comment] 2022-09-07 22:24
> I can confirm it doesn't work with Github Desktop, while it works from the terminal <img alt="image" width="449" src="https://user-images.githubusercontent.com/5140611/188522470-546be28b-3727-4919-9d8a-0c9de0b5f287.png">

You might need to add these steps: https://typicode.github.io/husky/#/?id=yarn-on-windows

-----------


I had a similar problem as this thread where `husky` would use my `msys2` installed bash instead of the one in the GH Desktop git (?) and it couldn't find a `cygwin1.dll`. Updating `msys2` made the error go away, and the pre-commit hook runs correctly.

I also tried your reproduction steps @ZhaoXiangXML, but I was able to commit without any errors. Running `git commit` from cmd shows that the hook was run, while in GitHub Desktop, it completes silently. (If anyone knows how to see the output in GH Desktop if there weren't any errors, that would be helpful as well).

**Comment by ZhaoXiangXML** [comment] 2022-09-09 04:31
> 

I just tried again with GitHub Desktop Version 3.0.7 on Windows and I still have the same problem.

Also you may find GitHub Desktop logs here:

![image](https://user-images.githubusercontent.com/719497/189272299-a451372b-d5e7-48c3-8225-64bf4c99e601.png)

**Comment by ZhaoXiangXML** [comment] 2022-09-09 04:38
I tied to change `.husky\pre-commit` to 

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm.cmd test

```

However I can't change the script like this because it won't work for Mac or Linux users.

I think it would be a bug of Github Desktop, I'll fire bug report later

**Comment by DoctorDerek** [comment] 2022-09-09 13:06
You might need to copy the npm binaries into PATH somehow.

**Comment by Saturate** [comment] 2022-10-19 16:51
> I tied to change `.husky\pre-commit` to
> 
> ```shell
> #!/usr/bin/env sh
> . "$(dirname -- "$0")/_/husky.sh"
> 
> npm.cmd test
> ```
> 
> It works as expected.
> 
> However I can't change the script like this because it won't work for Mac or Linux users.
> 
> I think it would be a bug of Github Desktop, I'll fire bug report later

Ran into some problems after installing WSL2. Did you do the same? Worked flawlessly before that.

**Comment by DoctorDerek** [comment] 2022-10-19 17:02
Just `npm run test` or `yarn test` would work cross-platform, but you'll have to help everyone get everything in the correct PATH for GitHub Desktop on all the platforms. It all works fine on my box, but I'm not using WSL2 because I don't want to break things and don't see the advantage. [The only disadvantage of developing on native windows is the line endings](https://medium.com/coding-at-dawn/how-windows-developers-can-use-lf-line-endings-a-gitattributes-poem-52f278b2f47f?sk=26643eca93f2c1a75072bdda4791ef35), in my opinion.

**Comment by Saturate** [comment] 2022-10-20 10:25
> Just `npm run test` or `yarn test` would work cross-platform, but you'll have to help everyone get everything in the correct PATH for GitHub Desktop on all the platforms. It all works fine on my box, but I'm not using WSL2 because I don't want to break things and don't see the advantage. [The only disadvantage of developing on native windows is the line endings](https://medium.com/coding-at-dawn/how-windows-developers-can-use-lf-line-endings-a-gitattributes-poem-52f278b2f47f?sk=26643eca93f2c1a75072bdda4791ef35), in my opinion.

I did not install WSL2 to develop on it, but I needed to have docker on my machine - and that uses it. It's pretty much a PATH / Github Desktop problem and not husky. Same thing happens if you try to sign your commits and you don't have gpg in the path that Github Desktop uses.

**Comment by ZhaoXiangXML** [comment] 2022-10-21 03:24
I also have wsl2 installed, I've not tried it before I install wsl2.

**Comment by ZhaoXiangXML** [comment] 2022-10-21 03:25
I've got the following reply from GitHub Support:

Hi Zhao,

Thanks for writing in! Apologies for the delay in our response! We're currently experiencing a higher than normal volume of support requests, and we appreciate your patience.

It looks like the error you're getting is a network-related error specific to Windows 10, and not necessarily a GitHub Desktop issue. This third-party article describes the possible fixes:

https://www.techinpost.com/an-address-incompatible-with-the-requested-protocol-was-used/

Please try them out and let me know how you get along.

Regards,
Peter
GitHub Support

**Comment by naytonbatista** [comment] 2022-11-17 01:22
> I can confirm it doesn't work with Github Desktop, while it works from the terminal

This work for me
Thanks

**Comment by naytonbatista** [comment] 2022-11-17 01:23
> Adding "C:\Program Files\Git\bin" to my PATH environment variable fixed this error at one point, [as I described on Stackoverflow](https://stackoverflow.com/a/67132704/2167762). Maybe try that?

This work for me
Thanks!

**Comment by typicode** [comment] 2023-01-03 05:37
Closing as the fix has been found :+1: PATH can be edited globally or in `~/.huskyrc` btw. `.huskyrc` doesn't require a reload since it's sourced every time a hook is run.

**Closed by typicode** 2023-01-03 05:37 UTC

**Comment by ThePiyushAggarwal** [comment] 2023-04-07 08:53
> 

A combination of this and this https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474 works for me

I used windows with nvm.

**Comment by ThePiyushAggarwal** [comment] 2023-04-07 08:54
> Adding "C:\Program Files\Git\bin" to my PATH environment variable fixed this error at one point, [as I described on Stackoverflow](https://stackoverflow.com/a/67132704/2167762). Maybe try that?

A combination of this and this https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474 works for me

I used windows with nvm.

**Comment by danieldbird** [comment] 2024-03-01 02:35
I had this for a good 5 months and couldn't figure it out. The solution for me was to make it executable, quit GH desktop, and it started working again.
`chmod a+x .husky/pre-commit`

**Comment by remacr** [comment] 2024-05-30 20:45
I solved it using the `which` command. I also use `nvm` so just make sure the global nvm version which is the one GitHub Desktop will use has `yarn` installed.

In your pre-commit file do the following:
```
$(which yarn) run pretty-quick --staged && $(which yarn) lint
```
