### ISSUE TITLE
core dump when installing with Node.js 12

### ISSUE THREAD

**Issue by piranna** [typicode/husky#479] opened 2019-04-24 08:56 UTC
I updated yesterday to Node.js 12, and today after removing `node_modules` folder and making `npm install`, husky is throwing core dumps when installing the hooks:

```sh
> husky@1.3.1 install /home/piranna/Trabajo/lingbe/client-core/node_modules/husky
> node husky install

husky > setting up git hooks


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffe72d576f0Illegal instruction (core dumped)

npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! husky@1.3.1 install: `node husky install`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the husky@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The npm debug log has only the next references:

```
30754 silly install husky@1.3.1
30755 info lifecycle husky@1.3.1~install: husky@1.3.1
30756 verbose lifecycle husky@1.3.1~install: unsafe-perm in lifecycle true
30757 verbose lifecycle husky@1.3.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/piranna/Trabajo/lingbe/client-core/node_modules/husky/node_modules/.bin:/home/piranna/Trabajo/lingbe/client-core/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/piranna/Android/Sdk/emulator:/home/piranna/Android/Sdk/tools:/home/piranna/Android/Sdk/tools/bin:/home/piranna/Android/Sdk/platform-tools:/home/piranna/Trabajo/Ventrata/depot_tools
30758 verbose lifecycle husky@1.3.1~install: CWD: /home/piranna/Trabajo/lingbe/client-core/node_modules/husky
30759 silly lifecycle husky@1.3.1~install: Args: [ '-c', 'node husky install' ]
30760 silly lifecycle husky@1.3.1~install: Returned: code: 132  signal: null
30761 info lifecycle husky@1.3.1~install: Failed to exec install script
```

**Comment by typicode** [comment] 2019-04-24 15:28
Hi @piranna,

Hmm I can't seem to reproduce. Do you also get the error with a new project:

```sh
mkdir test
cd test
npm init -y
git init
npm install husky -D
```

**Comment by piranna** [comment] 2019-04-24 15:46
I didn't try with a new project, but going back to Node.js v11.14.0 is working again. I opened an issue on Node.js repo at https://github.com/nodejs/node/issues/27385 and seems it could be related with https://github.com/nodejs/node/issues/27379.

**Comment by fraxken** [comment] 2019-04-24 20:35
Same problem here with Node.js v12.0.0 (On Windows 10).

**Comment by THernandez03** [comment] 2019-04-24 21:10
Same problem here with Node.js v12.0.0 (On Windows 10).

**Comment by bigslycat** [comment] 2019-04-24 23:39
Same problem here with Node.js v12.0.0 (On Ubuntu 19.04)

**Comment by wontoncc** [comment] 2019-04-25 04:38
Same problem here with Node.js v12.0.0 (On Windows 10).

**Comment by THernandez03** [comment] 2019-04-25 14:47
> Hi @piranna,
> 
> Hmm I can't seem to reproduce. Do you also get the error with a new project:
> 
> ```shell
> mkdir test
> cd test
> npm init -y
> git init
> npm install husky -D
> ```

Can't reproduce using this steps 🤔, everything was ok. 

Maybe a dependency of the project is causing a conflict, i will continue checking what is the problem.

**Comment by Svish** [comment] 2019-04-26 01:23
Same error here, on Windows 10.

* Pretty fresh project created today.
* `npm install husky` fails on Node.js v12.0.0, but does seem to work when reverting back to Node.js v11.14.0
* After successfully installing using v11, and reverting back to v12, `pre-commit` hooks seem to trigger and work fine.

So... I'm guess there's an incompatibility between husky package installation and node v12?

**Full debug log:**

* [2019-04-26T01_06_02_986Z-debug.log](https://github.com/typicode/husky/files/3119353/2019-04-26T01_06_02_986Z-debug.log)

**Output from console:**
```console
Y:\projects\foobar> npm install husky

> husky@2.1.0 install Y:\projects\foobar\node_modules\husky
> node husky install

husky > setting up git hooks


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000C05AFBD4F0npm ERR! code ELIFECYCLE
```

**Comment by kingfree** [comment] 2019-04-26 02:53
Same error on Windows 10, Node v12.0.0
```
[4/4] Building fresh packages...
[1/2] ⠠ husky
error C:\Users\***\node_modules\husky: Command failed.
Exit code: 3221225477
Command: node husky install
Arguments:
Directory: C:\Users\***\node_modules\husky
Output:
husky > setting up git hooks


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000BE02D1D660
```

**Comment by piranna** [comment] 2019-04-26 07:49
The problem is in the Node.js side, it's related to a bug in the ICU internationalization database used by v8 (three levels of indirection!!!). The only solution we could do here is to remove any magic related to default locale like usage of `Date.toLocaleString()` in the install script if we are using it. Anyway, we hope it gets fixed soon there...

**Comment by piranna** [comment] 2019-04-26 07:51
More info at https://github.com/nodejs/node/issues/27379, seems to be a somewhat important bug, there's a lot of people with problems due to it.

**Comment by bnoordhuis** [comment] 2019-04-28 09:25
The crash will be fixed in the next Node.js v12.x release. This issue can be closed.

**Comment by piranna** [comment] 2019-04-28 10:52
Let's wait until we confirm that it gets fixed.

**Comment by DRoet** [comment] 2019-04-30 09:14
FYI `12.1.0` is out now

**Comment by piranna** [comment] 2019-04-30 09:17
I had pending to write it here, I have checked it and seems to work with Node.js 12.1.0, seems the bug is fixed.

**Comment by typicode** [comment] 2019-05-01 16:45
Thanks for the @piranna, I'm closing this issue then :)

**Closed by typicode** 2019-05-01 16:45 UTC

**Comment by piranna** [comment] 2019-05-01 19:13
> Thanks for the update @piranna, I'm closing this issue then :)

You are welcome :-)
